### ISSUE TITLE
上傳資料標記 wait-for-review 的後續處理

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#115]
https://github.com/TaiBIF/camera-trap-api/issues/82

上傳資料至系統後，針對重覆的資料會在 uploadSession 及 annotation 標記 wait-for-review，需要說明前端處理的實作規格。

**Comment by cjk-halodule** [comment]
先至少確認上傳紀錄的溝通語言正確

**Comment by cjk-halodule** [comment]
![Screenshot 2019-06-03 15 03 09](https://user-images.githubusercontent.com/31983251/58782419-208a2080-8611-11e9-9ec3-9269cf629838.png)
剛上傳一筆 CSV 檔，沒有顯示狀態：
```
{ 
    "_id" : ObjectId("5cf4c5b22982f91f247ef6e0"), 
    "state" : "wait-for-review", 
    "project" : ObjectId("5ceb7e0df974a9ea6abb3da9"), 
    "user" : ObjectId("5ce50ba64d063e3575786ea7"), 
    "file" : ObjectId("5cf4c5b22982f915417ef6df"), 
    "cameraLocation" : ObjectId("5ceb7ea7f974a943fdbb3ecf"), 
    "createTime" : ISODate("2019-06-03T07:01:06.985+0000"), 
    "updateTime" : ISODate("2019-06-03T07:01:08.298+0000"), 
    "__v" : NumberInt(1)
}
```
需提示使用者 Overwrite http://bit.ly/2DMpjQR 或是 Cancel http://bit.ly/2IWj29k.

**Comment by f2ejack** [comment]
To: @cjk-halodule @moogoo78 
針對 upload-section-state, 建議修改為以下:
  processing: 'processing', // 處理中... (原來是: 處理中)
  waitForReview: 'wait-for-review', // 資料重複 (原來是: 等待確認覆蓋或取消)
  cancel: 'cancel', // 取消覆蓋
  success: 'success', // 上傳成功
  failure: 'failure', // 上傳失敗

另外, 針對可點選的連結文字 (ex: 查看), 增加一欄來放置, 並且加上底線讓 user 知道這是可以點選的. 目前包括以下的 actions:
  查看, 檢視錯誤, 補上傳影像擋, 確認覆蓋, 取消覆蓋

**Comment by cjk-halodule** [comment]
wait-for-review 不一定是資料重覆的情況喔，只是目前只有實作重覆資料的情況。然後這個 issue 是針對 'wait-for-review' 在前端的處理方式，不是要 review 所有的 uploadSession state.

**Comment by f2ejack** [comment]
Updated status
![螢幕快照 2019-06-05 下午10 54 54](https://user-images.githubusercontent.com/9169534/58966567-1587e980-87e5-11e9-94b5-45ca30d11304.png)

**Comment by f2ejack** [comment]
Updated up-to-date status:
- 確認取消: Done
- QA: Waiting for testing

**Comment by cjk-halodule** [comment]
![Screenshot 2019-06-06 22 34 39](https://user-images.githubusercontent.com/31983251/59041503-55190900-88ab-11e9-99fb-2d4fa786fc37.png)

目前確認覆蓋和取消覆蓋都沒有作用，因為連結沒有帶到 uploadSessionId.

![Screenshot 2019-06-06 22 36 33](https://user-images.githubusercontent.com/31983251/59041635-96a9b400-88ab-11e9-8dc6-bdd7488e579e.png)
此處字樣在目前請使用「資料部分或全部重覆，您要？」
