### ISSUE TITLE
欄位名稱根據計畫欄位設定

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#117]
![Screenshot 2019-05-11 20 05 24](https://user-images.githubusercontent.com/31983251/57569496-9511db00-7428-11e9-9065-742fa9e70d3d.png)

編輯區表單的欄位名稱應按計畫欄位設定：
![Screenshot 2019-05-08 17 03 59](https://user-images.githubusercontent.com/31983251/57569509-a4912400-7428-11e9-9b21-d988037a041c.png)

**Comment by cjk-halodule** [comment]
這個情況目前在 https://dev.camera-trap.tw/project/5cd6631299580e3eb17fe0f3/study-areas/5cd6643c99580e819b7fe123 有時出現，有時不會

**Comment by diabloevagto** [comment]
fixed #116

**Comment by cjk-halodule** [comment]
Verified.
