### ISSUE TITLE
annotations sheet 物種不會即時更新

### ISSUE THREAD

**Issue by diabloevagto** [TaiBIF/camera-trap-vueapp#125]
`http://localhost:8888/project/5cd6631299580e3eb17fe0f3/study-areas/5cdbc8b05d2c6a43f5a46680`

錯誤行為: 物種編輯之後不會更新在畫面上，但實際上的 vuex data 是有更新，需要編輯其他位置或者是再次點擊編輯的格子才會更新

預期行為: 編輯之後能馬上更新欄位資料

重現方式:
1. 進入編輯模式
2. 修改任意 column 的物種，此時物種格子都會即時更新
3. 修改其他欄位例如`性別`或`年齡` (下拉類型)，測試修改`備註` (文字輸入)也一樣
4. 此時修改物種就不會即時更新了
5. 此時關閉編輯模式再重進入也不會恢復正常，需要清相機位置清空或是重整畫面才會恢復正常

**Comment by diabloevagto** [comment]
造成這個問題的原因為在 `setSheetHeight` 共會有兩個值
- title: 使用者輸入的內容
- sp.title: 從後端更新回來的 annotations 的物種 title

正常情況兩者要是相同的，就算一開始還沒送出封包前會是不同的，但是封包更新回來之後就要是相同
不明情況會造成兩者一直是不同的，此時物種資料就一直是使用更新前的 `sp.title` 所以才會是舊的值

workaround 解法為，每次都判斷 `title` 跟 `sp.title` 是否相同，如果相同才用 `sp.title` 不相同的話就使用 `title` 使用者自己輸入的內容

此解法問題是會略過 `物種提示` 以及 `錯誤提示`

**Comment by cjk-halodule** [comment]
> 此解法問題是會略過 物種提示 以及 錯誤提示

意思是？

**Comment by diabloevagto** [comment]
因為 `title` 是一個字串只有使用者輸入的文字內容，並沒有 system code(物種提示) 跟 failures(錯誤提示)

**Comment by cjk-halodule** [comment]
Verified.
