### ISSUE TITLE
The file type isn't project-cover-image at the data upload page.

### ISSUE THREAD

**Issue by kelp404** [TaiBIF/camera-trap-vueapp#127]
# 錯誤回報

### 重現步驟

1. 到任一計畫的檔案上傳頁面
https://dev.camera-trap.tw/project/5cdcdcd818ad1133db79620f/upload
2.
3.
...

### 預期行為

The type should be `annotation-image`.

### 實際行為

The type is `project-cover-image`.

## 錯誤或提示訊息

<img width="1172" alt="螢幕快照 2019-05-17 下午6 10 04" src="https://user-images.githubusercontent.com/1680868/57921209-6f288280-78cf-11e9-9273-3fe630d75b0c.png">

### 作業環境
**作業系統及版本：**
<pre>OS X<code>

</code></pre>

**瀏覽器及版本：**
<pre>Chrome<code>

</code></pre>

**Comment by oahehc** [comment]
這 format 必須給個 👍

**Comment by moogoo78** [comment]
這個是不是應該 close 了 https://github.com/TaiBIF/camera-trap-vueapp/blob/master/src/pages/Project/ProjectUpload/UploadProcess.vue#L227-L238
