### ISSUE TITLE
7.3.2 資料篩選結果頁面中右下角"進階標注"按鈕的後續行為及頁面

### ISSUE THREAD

**Issue by f2ejack** [TaiBIF/camera-trap-vueapp#142]
<img width="435" alt="螢幕快照 2019-05-20 上午2 13 21" src="https://user-images.githubusercontent.com/9169534/57986303-ba948980-7aa5-11e9-9aa0-5f1b1aa4491e.png">

**Comment by cjk-halodule** [comment]
這個功能先關掉，不顯示。
