### ISSUE TITLE
新增檔案結構說明

### ISSUE THREAD

**Issue by f2ejack** [TaiBIF/camera-trap-vueapp#143]
強烈建議針對專案的**檔案結構**透過 Markdown 語法**於各個資料夾/檔案**撰寫 Readme.md 給予概略說明, 如此可以讓現階段或日後參與的工程師很快上手. 以 project 相關頁面為例:

## src/pages/
包含所有的頁面

### src/pages/project/
"計畫"頁面 (參考 WF 1)

#### src/pages/project/EditProject/
"OOO"頁面 (參考 WF 1-1)

## src/prose/
...

## src/router
...
 
## src/service
...

## src/store
...

... 等等

**Comment by oahehc** [comment]
除了後續新增的 prose 沒更新到, 其他應該本來就有放了
![image](https://user-images.githubusercontent.com/13633490/57990018-07438900-7ad5-11e9-8ff3-25e390f116e4.png)
