### ISSUE TITLE
把拉資料的程式放在固定的地方

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#15]
https://github.com/TaiBIF/camera-trap-webapp/blob/0d9e8d89160f7579e86b1bcead1a07e961471a75/src/pages/search/views/SearchResult.vue#L935

每個元件拉資料的時間統一會比較好。
(元件建立後才拉資料會變成每個元件都要有自己實作「載入中」的介面)

**Comment by cjk-halodule** [comment]
上次討論記得有決定拉資料的和前端顯示提示的順序了，請 @diabloevagto @oahehc 確認一下是否有 sync 這部分了。

**Comment by oahehc** [comment]
依照上次討論統一在 mounted lifecycle fetch data,
但如果是要依照 user interaction trigger 的部分則需照實際需求處理。

**Comment by cjk-halodule** [comment]
Seems located in service directory. That's useful.
