### ISSUE TITLE
主選單切換 console 報錯

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#164]
![Screenshot 2019-05-25 18 30 10](https://user-images.githubusercontent.com/31983251/58368141-71b45900-7f1b-11e9-9ee3-537479269d48.png)

從物種名稱錯誤的連結切到聯絡我們頁面 console 報錯，主選單切換也有一樣的情況。

**Comment by diabloevagto** [comment]
這不用切換只要打開就會有錯誤

**Comment by oahehc** [comment]
這是 notification response 有缺欄位, 或是資料結構變了 (少了 studyArea.id)
另外我在這個 PR https://github.com/TaiBIF/camera-trap-vueapp/pull/165 有處理避免出現錯誤, 
但只是避免了 error, 欄位還是需要補上, 建議重新 review 一下 notification response 所有 type 應該要回覆的資料

**Comment by f2ejack** [comment]
剛剛再次於 Chrome 與 Firefox 檢查一次, Console 已經沒有錯誤訊息了.
