### ISSUE TITLE
資料分頁問題

### ISSUE THREAD

**Issue by oahehc** [TaiBIF/camera-trap-vueapp#169]
#### 問題描述
部分 API 目前有限制回傳資料筆數 size, 但前端畫面目前沒有規劃分頁/infinite load 來分批載入資料
已知部分有 projects / camera-location / data-field 

#### 建議修正
1. 如果畫面操作可以允許分段載入, 可考慮做 pagination or infinite load
	* 如果資料量大到需要分段載入, 可評估是否需要 filter/search 功能
2. 如果畫面必須要一次取得所有資料, 建議要新增 api 可以取得完整資料, 並限制最大資料筆數

**Comment by cjk-halodule** [comment]
以目前的 API 前端是否已經可以利用 pagination，在捲動觸底時再載入 api 下一頁？剛在 demo 找不到被新計畫擠下去的計畫蠻糗，然後排序也不太有用...

**Comment by f2ejack** [comment]
所以, Spec 是要做成 Lazy Loading 的效果, 是嗎?
