### ISSUE TITLE
首頁右上方navbar在手機等小尺寸顯示異常

### ISSUE THREAD

**Issue by LeoLiu1209** [TaiBIF/camera-trap-vueapp#170]
# 錯誤回報

### 問題簡述
進入到首頁後，將畫面利用 chrome dev 調整畫面比例到任一手機畫面瀏覽，**右上方的navbar**總是出現 "x" ，會讓使用者看到"x"不知所云，取而代之的應該是漢堡選單，但此現象當點擊"x"後便會恢復正常

![image](https://github.com/LeoLiu1209/imageCollection/blob/master/TaiBIF_narbar_bug.gif?raw=true)
 

### 重現步驟

1.進入首頁
2.畫面切到手機瀏覽
3.不要點擊右上角 narbar 就會看到"x"而不是"三"的漢堡選單

### 預期行為
初始狀態未點擊選單時應為漢堡選單，而不是"x"
![image](https://user-images.githubusercontent.com/15647660/52166619-95744900-274a-11e9-9342-9f6f0ce4e306.png)

### 實際行為
初始狀態未點擊選單時，卻出現"x" navbar icon

### 作業環境
**作業系統及版本：**
<pre><code>windows 7
</code></pre>

**瀏覽器及版本：**
<pre><code>Chrome  Version 71.0.3578.98 (Official Build) (64-bit)
</code></pre>

**Comment by cjk-halodule** [comment]
謝謝 @LeoLiu1209 回報 👍

這是舊版前端的 defect
@diabloevagto 因為靜態頁面還是要能支援小尺寸，所以麻煩看一下目前這版是否有類似的問題。

**Comment by oahehc** [comment]
目前這版應該沒這問題, 
但有個延伸的問題是有那些畫面需要 RWD, `幫助` 內的頁面是否都需要？
另外順帶提一下, 如果有 SEO 的需求, 可能所有要開放的頁面都要考慮 RWD, 
因為 mobile friendly 基本上已經是 SEO 必備

![image](https://user-images.githubusercontent.com/13633490/58369938-d4b1ea00-7f33-11e9-9d2f-21e87083eff1.png)

**Comment by cjk-halodule** [comment]
同意。幫助內的頁面都會需要。其它單元的我們下階段設計時再考慮要支援到什麼程度。
那麼這個 issue 先可以 close.
