### ISSUE TITLE
編輯常見物種順序頁面 console 報錯

### ISSUE THREAD

**Issue by f2ejack** [TaiBIF/camera-trap-vueapp#177]
#### 問題簡述
載入"編輯常見物種順序"頁面時, Console 出現錯誤訊息

#### 重現步驟
1. 點選 NavHeader 的"計畫總覽"選項
2. 點選任何一計畫
3. 點選"計畫管理"按鈕
4. 點選"計畫管理"選項
5. 點選"編輯設定"選項
6. 點選"編輯常見物種順序"鏈結

#### 預期行為
Console 沒有錯誤訊息

#### 實際行為
Console 出現錯誤訊息

### 錯誤或提示訊息
<img src="https://user-images.githubusercontent.com/9169534/58389468-6cf7be00-805d-11e9-8876-a32e7d3050ce.png">

#### 作業環境
**作業系統及版本：**
<pre><code>macOS Mojave 10.14.5</code></pre>

**瀏覽器及版本：**
<pre><code>Firefox Quantum 67.0 (64 位元)</code></pre>

#### 其它
N/A

**Comment by cjk-halodule** [comment]
Closed by 6210093
