### ISSUE TITLE
計畫資料頁預設篩選範圍為計畫資料 開始及結束 時間

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#178]
![Screenshot 2019-05-27 11 15 03](https://user-images.githubusercontent.com/31983251/58393375-041a4100-8071-11e9-8f0d-8d0a8e2d88e2.png)

使用 /projects/:projectId 的
```
  "latestAnnotationTime": "2018-01-11T06:43:50.000Z",
  "oldestAnnotationTime": "2017-01-10T03:48:48.000Z"
```
為範圍可讓使用者一進入就看得到資料。
但若是剛上傳則不會立刻有。無妨。

**Comment by cjk-halodule** [comment]
這兩者也是在計畫選定時需要連動決定時間範圍的例子。

![Screenshot 2019-05-27 20 51 13](https://user-images.githubusercontent.com/31983251/58420922-2e93ea80-80c1-11e9-9f96-367b05e87d6d.png)
![Screenshot 2019-05-27 20 52 16](https://user-images.githubusercontent.com/31983251/58420969-54b98a80-80c1-11e9-8fc9-64e9f95a5de4.png)

**Comment by kelp404** [comment]
1. 資料篩選與下載是跨計畫的。
2. 時間並非必填欄位，不填時間跟把 annotation 的時間範圍帶進去搜尋結果會是一樣的。

**Comment by cjk-halodule** [comment]
這是一個幫助使用者的想法，因為一開始並不曉得那個時間範圍會有資料，所以當有一個計畫、樣區及相機位置被選定，時間選項的調整可以提示目前選取條件的時間，不過這個時候前前端並不需要預設任何值，只是顯示，只有在使用者真的去打字或是動到 picker，時間才會帶到送出的查詢中。這樣可以？

**Comment by diabloevagto** [comment]
我自己覺得 placeholder 是明確告訴使用者要怎麼輸入，而不是呈現一個數值給使用者看
這樣反而為讓使用者分不清楚那到底是提醒還是預設值，而且 placeholder 是一個比較淺色的呈現不是很能夠清楚的表示是提示還是自己輸入的值

**Comment by cjk-halodule** [comment]
目前這個 placeholder 顯然是預設撈資料的時間，所以例如當有一些相機位置點選之後，資料時間在 2011 年，就會有該位置沒資料的錯覺，但使用者其實不見得會知道該相機位置的何時有資料。

解決方式建議是預設以計畫的
```
 "latestAnnotationTime": "2018-01-11T06:43:50.000Z",
  "oldestAnnotationTime": "2017-01-10T03:48:48.000Z"
```
來決定預設的資料載入範圍。placeholder 也需要反應此範圍。

**Comment by diabloevagto** [comment]
這個有時區問題嗎？直接轉成 GMT+8 ?

**Comment by cjk-halodule** [comment]
API 出來的都是 UTC 喔 所以要轉

**Comment by diabloevagto** [comment]
目前時間範圍會有個問題，缺少最後一分鐘 (23:59 ~ 00:00)
也一起順便修正
