### ISSUE TITLE
1 首頁「開始使用」總是連到 orcid

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#183]
首頁「開始使用」總是連到 orcid

**Comment by oahehc** [comment]
這頁面我做的所以我來處理好了. 會改成
* uesr 未登入 -> 開啟登入視窗 (orcid)
* user 已登入 -> 進入計畫總覽

**Comment by cjk-halodule** [comment]
Fixed by 
6cb1589
