### ISSUE TITLE
2.1 新增計畫頁面的計畫時間點選日期與顯示日期不一致

### ISSUE THREAD

**Issue by f2ejack** [TaiBIF/camera-trap-vueapp#187]
#### 問題簡述
![screenshot-2019-05-28 上午11 33 30](https://user-images.githubusercontent.com/9169534/58449158-def30480-813c-11e9-93bf-3e6802c26fd4.png)

#### 重現步驟

1.
2.
3.
...

#### 作業環境
**作業系統及版本：**
<pre><code>

</code></pre>

**瀏覽器及版本：**
<pre><code>

</code></pre>

**Comment by moogoo78** [comment]
@oahehc 好像加了 UTC+0，這個問題就跑出來了，但是不知道為什麼其他地方的日期都是好的，只有這一頁會這樣？
https://github.com/TaiBIF/camera-trap-vueapp/blob/master/src/utils/dateHelper.js#L4

**Comment by oahehc** [comment]
ref: https://github.com/TaiBIF/camera-trap-vueapp/issues/210#issuecomment-497317206, https://github.com/TaiBIF/camera-trap-vueapp/issues/205#issuecomment-496914492
照目前 @kelp404 @dca 的說法是取出資料後依照 user 時區換算, 所以先前設定 UTC+0 應該要移除.

但是這樣會造成每個 user 看到的資料不一致, 並出現之前 @cjk-halodule 回報的這類問題. https://github.com/TaiBIF/camera-trap-vueapp/issues/205#issuecomment-496935506
應如何調整再請 @cjk-halodule 協助評估了

**Comment by moogoo78** [comment]
要不要把 default 設定 UTC+8，讓client 端時間都固定。

**Comment by oahehc** [comment]
如果前端 default 設 UTC+8, 後端 API 有些可能也要同步調整, 例如取 2019 的資料時要給 UTC+8 的 2019.

**Comment by cjk-halodule** [comment]
Confixed.
