### ISSUE TITLE
5.7 檔案上傳的錯誤處理

### ISSUE THREAD

**Issue by moogoo78** [TaiBIF/camera-trap-vueapp#193]
### 錯誤回報

上傳 csv 後資料沒有顯示

#### 問題簡述

上傳 csv 檔案格式錯誤 (樣區名稱對不起來)
沒有跳出錯誤訊息, 卻顯示上傳成功

#### 其它
參考: https://github.com/TaiBIF/camera-trap-vueapp/issues/63

**Comment by kelp404** [comment]
之前有說過沒辦法馬上算出來，會呈現在 upload session 上。

**Comment by cjk-halodule** [comment]
這裡的問題在使用者通常會視「檔案上傳」為「檔案上傳加處理」，所以上傳訊息的成功會被當作處理也完成。此處只是文字上將http 200「上傳成功」改為「系統已收到檔案」，然後將上傳紀錄的頁面中的 processing 改呈現為「處理中」。

**Comment by cjk-halodule** [comment]
![Screenshot 2019-06-03 15 20 00](https://user-images.githubusercontent.com/31983251/58783373-54664580-8613-11e9-9c4a-1cc0a65bf671.png)

此處的「上傳中」應為「處理中」

**Comment by f2ejack** [comment]
與 Issue #244 相同
