### ISSUE TITLE
4.2 選擇相機位置後所顯示的資料列表筆數不正確

### ISSUE THREAD

**Issue by f2ejack** [TaiBIF/camera-trap-vueapp#195]
重現步驟:
1. 計畫總覽 > 點選"九份二山生物多樣性調查及長期監測模式之建立-哺乳類(107)"計畫 > 計入該計畫的頁面
2. 點選左側的 J01 相機連結, 姐接著在右邊的上方勾選"全部相機"選項
3. 此時下方會開始載入所有的資料筆數, 但是**畫面上僅顯示前10餘筆資料, 畫面捲動至底部時, 依然們有載入後續的資料** (PS: 但是下方顯示 您正在檢視：第1 - 49筆)

<img width="1151" alt="螢幕快照 2019-05-30 上午3 48 53" src="https://user-images.githubusercontent.com/9169534/58586625-191feb80-828e-11e9-9f29-8dcb48730b1f.png">

**Comment by cjk-halodule** [comment]
@f2ejack  在不換頁的情況下，載入後續的資料最終是 49 筆嗎？

**Comment by f2ejack** [comment]
是的，49筆。

**Comment by cjk-halodule** [comment]
那就沒有錯，這是預期中 handsontable 的行為。
