### ISSUE TITLE
4.3 A進入某樣區的編輯模式後，B如果也在同一樣區且未重整，也還是可以進入編輯模式

### ISSUE THREAD

**Issue by g11145590** [TaiBIF/camera-trap-vueapp#197]
(缺重現步驟)

**Comment by diabloevagto** [comment]
有更清楚地重現手法嗎？

**Comment by cjk-halodule** [comment]
@diabloevagto 這個問題的解法可以是：
其他人在介面鎖定狀態尚未更新的狀態下要進入編輯模式時，前端再查詢一次相機是否在鎖定狀態，並更新一次左欄的樣區列表。

若是鎖定，則跳出對話框說明「此相機位置剛進入鎖定狀態，正由 xxx 編輯中。」按鈕就是「我知道了」。

**Comment by diabloevagto** [comment]
`正由 xxx 編輯中` 這一段是否要拿掉？因為有可能選好幾個相機各自都是不同的人在編輯

我會在鎖定失敗後去更新相機位置狀態，使用者在自己滑鼠移上去就可以知道是誰了

**Comment by cjk-halodule** [comment]
不是喔，這個 issue 是有人要編輯一個已經有人在編輯的相機位置，但是因為左欄樣區鎖定狀態尚未更新，所以只會有一個相機位置，故呈現是誰在編輯應該不會有你提到的問題。

**Comment by cjk-halodule** [comment]
摘要和 @diabloevagto 討論完的解法
1. 進入編模式時，前端會再確認該相機位置，或是所選的多個相機位置中，有正被鎖定者。
2. 若有，則跳出對話框，顯示「此相機位置剛進入鎖定狀態，無法進入編輯模式。」
3. 接著觸發頁面的更新，包含左欄樣區，讓使用者能看到鎖定圖示，想知道誰在編輯也可以滑入得知。

**Comment by diabloevagto** [comment]
> 摘要和 @diabloevagto 討論完的解法
> 
> 1. 進入編模式時，前端會再確認該相機位置，或是所選的多個相機位置中，有正被鎖定者。
> 2. 若有，則跳出對話框，顯示「此相機位置剛進入鎖定狀態，無法進入編輯模式。」
> 3. 接著觸發頁面的更新，包含左欄樣區，讓使用者能看到鎖定圖示，想知道誰在編輯也可以滑入得知。

關於 #3 左側樣區選單的鎖定圖示滑入並不會知道實在編輯，他是要滑入上方的相機位置看是誰編輯
另外 http://bit.ly/2DIvx4f 這隻 api 取得的鎖定資訊是 `isLockedAllCameraLocation` ，請確認這樣是否符合需求
