### ISSUE TITLE
4.2 離開相機位置的編輯模式頁面後, 不會自動解除鎖定的狀態

### ISSUE THREAD

**Issue by f2ejack** [TaiBIF/camera-trap-vueapp#198]
重現問題步驟:
1. 計畫管理 > 點選某一個計畫 > 選擇某一個相機位置 > 點選"進入編輯模式" (此時左邊選單出現Lock的圖示)
2. 直接離開"相機編輯模式"頁面
3. 此時左邊選單的Lock圖示並沒有消失

**Comment by cjk-halodule** [comment]
Related #40

**Comment by f2ejack** [comment]
To @diabloevagto 根據 [issue-#40](https://github.com/TaiBIF/camera-trap-vueapp/issues/40), 這一個 issue 目前依然尚未被解決. 所以需要你的協助處理.

**Comment by cjk-halodule** [comment]
@f2ejack  目前有30分鐘自動解除鎖定狀態的功能，請測試後確認此行為是否正常運作，可以的話就關閉此 issue，謝謝。

**Comment by f2ejack** [comment]
經測試, 目前進入編輯模式, 30分鐘後會彈出 Modal (如下圖).
![螢幕快照 2019-06-10 上午11 45 02](https://user-images.githubusercontent.com/9169534/59184677-38c5e680-8ba1-11e9-8f62-f6a4a98496a9.png)
