### ISSUE TITLE
物種排序頁面 console 報錯

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#202]
![Screenshot 2019-05-28 11 44 46](https://user-images.githubusercontent.com/31983251/58449415-0a2a2380-813e-11e9-85b8-6e531249c148.png)

**Comment by cjk-halodule** [comment]
但目前功能似乎正常。

**Comment by cjk-halodule** [comment]
Duplicated #177

**Comment by f2ejack** [comment]
剛剛測試, 還是有報錯耶!! 已經重新登出&登入.

16vue.runtime.esm.js?2b0e:619 [Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

found in

---> <Species> at src/pages/Project/EditProject/Species.vue
       <DataFields> at src/pages/Project/EditProject/DataFields.vue
         <Setting> at src/pages/Project/EditProject/Setting.vue
           <Index> at src/pages/Project/EditProject/index.vue
             <Detail> at src/pages/Project/Detail.vue
               <Index> at src/pages/Project/index.vue
                 <App> at src/App.vue
                   <Root>
warn @ vue.runtime.esm.js?2b0e:619
_createElement @ vue.runtime.esm.js?2b0e:3384
createElement @ vue.runtime.esm.js?2b0e:3353
vm._c @ vue.runtime.esm.js?2b0e:3485
(anonymous) @ Species.vue?5ad1:32
renderList @ vue.runtime.esm.js?2b0e:2630
render @ Species.vue?5ad1:31
Vue._render @ vue.runtime.esm.js?2b0e:3542
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
run @ vue.runtime.esm.js?2b0e:4548
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4304
(anonymous) @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4396
update @ vue.runtime.esm.js?2b0e:4538
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
proxySetter @ vue.runtime.esm.js?2b0e:4625
click @ DataFields.vue?bcb1:36
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6911
15vue.runtime.esm.js?2b0e:619 [Vue warn]: Duplicate keys detected: '[object Object]'. This may cause an update error.

found in

---> <Species> at src/pages/Project/EditProject/Species.vue
       <DataFields> at src/pages/Project/EditProject/DataFields.vue
         <Setting> at src/pages/Project/EditProject/Setting.vue
           <Index> at src/pages/Project/EditProject/index.vue
             <Detail> at src/pages/Project/Detail.vue
               <Index> at src/pages/Project/index.vue
                 <App> at src/App.vue
                   <Root>
warn @ vue.runtime.esm.js?2b0e:619
checkDuplicateKeys @ vue.runtime.esm.js?2b0e:6240
updateChildren @ vue.runtime.esm.js?2b0e:6178
patchVnode @ vue.runtime.esm.js?2b0e:6313
patch @ vue.runtime.esm.js?2b0e:6476
Vue._update @ vue.runtime.esm.js?2b0e:3942
_update @ vue.runtime.esm.js?2b0e:8240
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
run @ vue.runtime.esm.js?2b0e:4548
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4304
(anonymous) @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4396
update @ vue.runtime.esm.js?2b0e:4538
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
proxySetter @ vue.runtime.esm.js?2b0e:4625
click @ DataFields.vue?bcb1:36
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6911
16vue.runtime.esm.js?2b0e:619 [Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

found in

---> <Species> at src/pages/Project/EditProject/Species.vue
       <DataFields> at src/pages/Project/EditProject/DataFields.vue
         <Setting> at src/pages/Project/EditProject/Setting.vue
           <Index> at src/pages/Project/EditProject/index.vue
             <Detail> at src/pages/Project/Detail.vue
               <Index> at src/pages/Project/index.vue
                 <App> at src/App.vue
                   <Root>
warn @ vue.runtime.esm.js?2b0e:619
_createElement @ vue.runtime.esm.js?2b0e:3384
createElement @ vue.runtime.esm.js?2b0e:3353
vm._c @ vue.runtime.esm.js?2b0e:3485
(anonymous) @ Species.vue?5ad1:32
renderList @ vue.runtime.esm.js?2b0e:2630
render @ Species.vue?5ad1:31
Vue._render @ vue.runtime.esm.js?2b0e:3542
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
run @ vue.runtime.esm.js?2b0e:4548
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4304
(anonymous) @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4396
update @ vue.runtime.esm.js?2b0e:4538
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
setProjectSpecies @ projects.js?b326:156
wrappedMutationHandler @ vuex.esm.js?2f62:714
commitIterator @ vuex.esm.js?2f62:382
(anonymous) @ vuex.esm.js?2f62:381
_withCommit @ vuex.esm.js?2f62:512
commit @ vuex.esm.js?2f62:380
boundCommit @ vuex.esm.js?2f62:325
local.commit @ vuex.esm.js?2f62:668
_callee8$ @ projects.js?b326:236
tryCatch @ runtime.js?96cf:45
invoke @ runtime.js?96cf:271
prototype.<computed> @ runtime.js?96cf:97
asyncGeneratorStep @ asyncToGenerator.js?3b8d:5
_next @ asyncToGenerator.js?3b8d:27
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?3b8d:15
_next @ asyncToGenerator.js?3b8d:27
(anonymous) @ asyncToGenerator.js?3b8d:34
F @ _export.js?63b6:36
(anonymous) @ asyncToGenerator.js?3b8d:23
getProjectSpecies @ projects.js?b326:184
wrappedActionHandler @ vuex.esm.js?2f62:721
dispatch @ vuex.esm.js?2f62:428
boundDispatch @ vuex.esm.js?2f62:322
local.dispatch @ vuex.esm.js?2f62:651
mappedAction @ vuex.esm.js?2f62:924
mounted @ Species.vue?3ed2:90
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
callHook @ vue.runtime.esm.js?2b0e:4213
insert @ vue.runtime.esm.js?2b0e:3139
invokeInsertHook @ vue.runtime.esm.js?2b0e:6340
patch @ vue.runtime.esm.js?2b0e:6559
Vue._update @ vue.runtime.esm.js?2b0e:3942
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
run @ vue.runtime.esm.js?2b0e:4548
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4304
(anonymous) @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4396
update @ vue.runtime.esm.js?2b0e:4538
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
proxySetter @ vue.runtime.esm.js?2b0e:4625
click @ DataFields.vue?bcb1:36
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6911
15vue.runtime.esm.js?2b0e:619 [Vue warn]: Duplicate keys detected: '[object Object]'. This may cause an update error.

found in

---> <Species> at src/pages/Project/EditProject/Species.vue
       <DataFields> at src/pages/Project/EditProject/DataFields.vue
         <Setting> at src/pages/Project/EditProject/Setting.vue
           <Index> at src/pages/Project/EditProject/index.vue
             <Detail> at src/pages/Project/Detail.vue
               <Index> at src/pages/Project/index.vue
                 <App> at src/App.vue
                   <Root>
warn @ vue.runtime.esm.js?2b0e:619
checkDuplicateKeys @ vue.runtime.esm.js?2b0e:6240
updateChildren @ vue.runtime.esm.js?2b0e:6178
patchVnode @ vue.runtime.esm.js?2b0e:6313
patch @ vue.runtime.esm.js?2b0e:6476
_update @ vue.runtime.esm.js?2b0e:8232
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
run @ vue.runtime.esm.js?2b0e:4548
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4304
(anonymous) @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4396
update @ vue.runtime.esm.js?2b0e:4538
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
setProjectSpecies @ projects.js?b326:156
wrappedMutationHandler @ vuex.esm.js?2f62:714
commitIterator @ vuex.esm.js?2f62:382
(anonymous) @ vuex.esm.js?2f62:381
_withCommit @ vuex.esm.js?2f62:512
commit @ vuex.esm.js?2f62:380
boundCommit @ vuex.esm.js?2f62:325
local.commit @ vuex.esm.js?2f62:668
_callee8$ @ projects.js?b326:236
tryCatch @ runtime.js?96cf:45
invoke @ runtime.js?96cf:271
prototype.<computed> @ runtime.js?96cf:97
asyncGeneratorStep @ asyncToGenerator.js?3b8d:5
_next @ asyncToGenerator.js?3b8d:27
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?3b8d:15
_next @ asyncToGenerator.js?3b8d:27
(anonymous) @ asyncToGenerator.js?3b8d:34
F @ _export.js?63b6:36
(anonymous) @ asyncToGenerator.js?3b8d:23
getProjectSpecies @ projects.js?b326:184
wrappedActionHandler @ vuex.esm.js?2f62:721
dispatch @ vuex.esm.js?2f62:428
boundDispatch @ vuex.esm.js?2f62:322
local.dispatch @ vuex.esm.js?2f62:651
mappedAction @ vuex.esm.js?2f62:924
mounted @ Species.vue?3ed2:90
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
callHook @ vue.runtime.esm.js?2b0e:4213
insert @ vue.runtime.esm.js?2b0e:3139
invokeInsertHook @ vue.runtime.esm.js?2b0e:6340
patch @ vue.runtime.esm.js?2b0e:6559
Vue._update @ vue.runtime.esm.js?2b0e:3942
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
run @ vue.runtime.esm.js?2b0e:4548
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4304
(anonymous) @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4396
update @ vue.runtime.esm.js?2b0e:4538
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
proxySetter @ vue.runtime.esm.js?2b0e:4625
click @ DataFields.vue?bcb1:36
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6911
15vue.runtime.esm.js?2b0e:619 [Vue warn]: Duplicate keys detected: '[object Object]'. This may cause an update error.

found in

---> <Species> at src/pages/Project/EditProject/Species.vue
       <DataFields> at src/pages/Project/EditProject/DataFields.vue
         <Setting> at src/pages/Project/EditProject/Setting.vue
           <Index> at src/pages/Project/EditProject/index.vue
             <Detail> at src/pages/Project/Detail.vue
               <Index> at src/pages/Project/index.vue
                 <App> at src/App.vue
                   <Root>
warn @ vue.runtime.esm.js?2b0e:619
checkDuplicateKeys @ vue.runtime.esm.js?2b0e:6240
updateChildren @ vue.runtime.esm.js?2b0e:6178
patchVnode @ vue.runtime.esm.js?2b0e:6313
patch @ vue.runtime.esm.js?2b0e:6476
Vue._update @ vue.runtime.esm.js?2b0e:3942
_update @ vue.runtime.esm.js?2b0e:8240
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
run @ vue.runtime.esm.js?2b0e:4548
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4304
(anonymous) @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4396
update @ vue.runtime.esm.js?2b0e:4538
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
setProjectSpecies @ projects.js?b326:156
wrappedMutationHandler @ vuex.esm.js?2f62:714
commitIterator @ vuex.esm.js?2f62:382
(anonymous) @ vuex.esm.js?2f62:381
_withCommit @ vuex.esm.js?2f62:512
commit @ vuex.esm.js?2f62:380
boundCommit @ vuex.esm.js?2f62:325
local.commit @ vuex.esm.js?2f62:668
_callee8$ @ projects.js?b326:236
tryCatch @ runtime.js?96cf:45
invoke @ runtime.js?96cf:271
prototype.<computed> @ runtime.js?96cf:97
asyncGeneratorStep @ asyncToGenerator.js?3b8d:5
_next @ asyncToGenerator.js?3b8d:27
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?3b8d:15
_next @ asyncToGenerator.js?3b8d:27
(anonymous) @ asyncToGenerator.js?3b8d:34
F @ _export.js?63b6:36
(anonymous) @ asyncToGenerator.js?3b8d:23
getProjectSpecies @ projects.js?b326:184
wrappedActionHandler @ vuex.esm.js?2f62:721
dispatch @ vuex.esm.js?2f62:428
boundDispatch @ vuex.esm.js?2f62:322
local.dispatch @ vuex.esm.js?2f62:651
mappedAction @ vuex.esm.js?2f62:924
mounted @ Species.vue?3ed2:90
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
callHook @ vue.runtime.esm.js?2b0e:4213
insert @ vue.runtime.esm.js?2b0e:3139
invokeInsertHook @ vue.runtime.esm.js?2b0e:6340
patch @ vue.runtime.esm.js?2b0e:6559
Vue._update @ vue.runtime.esm.js?2b0e:3942
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
run @ vue.runtime.esm.js?2b0e:4548
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4304
(anonymous) @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4396
update @ vue.runtime.esm.js?2b0e:4538
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
proxySetter @ vue.runtime.esm.js?2b0e:4625
click @ DataFields.vue?bcb1:36
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6911

**Comment by oahehc** [comment]
PR 還沒 merge, merge 後應該就正常了
![image](https://user-images.githubusercontent.com/13633490/58521356-0f937680-81ef-11e9-97a6-74cb7145a09c.png)

**Comment by cjk-halodule** [comment]
Closed by https://github.com/TaiBIF/camera-trap-vueapp/commit/621009348a409f1559b698c10b678bebbe352751
