### ISSUE TITLE
OI 值標題及單位的明確表示

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#203]
![OI 值](https://user-images.githubusercontent.com/31983251/58467579-905e5e00-816e-11e9-885c-1c9af133d412.png)

待進一步說明數值的呈現 (NaN 及 infinity) 及計算結果標題。

**Comment by moogoo78** [comment]
fixed https://github.com/TaiBIF/camera-trap-vueapp/commit/8b13d353547ac60a43fcd8ea62ad57d1534e74f1
