### ISSUE TITLE
3.6 新增成員除了清單更新外應有下方的新增成功提示

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#204]
![加入成員](https://user-images.githubusercontent.com/31983251/58467961-36aa6380-816f-11e9-84fd-e14f0d7ebb86.png)

**Comment by f2ejack** [comment]
以下是目前的作法:
1. 填入成員的 ORCiD 或 E-mail 資料, 按下"加入"後會 Call 後端 API 做檢查, 果有任何錯誤, 會在欄位下方直接顯示"請再次檢查資料是否正確"
2. 按下右下方的"儲存設定"按鈕, 如果儲存成功 (status === 200), 則直接跳頁到"創用CC授權"頁面 (這是之前的 behavior, 暫時不去更動它)
3. 按下右下方的"儲存設定"按鈕, 如果儲存不成功 (status !== 200), 則顯示錯誤訊息在頁面的左下方

**Comment by cjk-halodule** [comment]
請 @f2ejack ：
- [ ] 將儲存設定按了之後的行為不再跳到下一個選單
- [ ] 頁面中的資料未變動前，儲存設定按鈕鎖定
- [ ] 頁面中的資料變動後，儲存前，按鈕為可按及橘色
- [ ] 按了儲存設定後，200 回傳儲存成功（不再跳頁），將按鈕回復鎖定狀態
- [ ] 按了儲存設定後，4xx 回傳操作失敗（不再跳頁），顯示錯誤訊息及指示

**Comment by f2ejack** [comment]
Hi @cjk-halodule ,
抱歉, 剛剛才看到了 issue comment, 發現這已經不完全是 issue 了, 而是包含 feature requirement (因為原本的 wireframe 並無這樣的 spec.), 而且將一個原本小 issue 發散成許多的 issues 或 features, 這是軟體開發流程的一大忌諱 -- 會造成 issue 無法 close. 
對了, issue 越小越單一越好, 這是 QA 界的基本規則, 最好不要一個 issue 包含更多 issues (這也是我過去在 Trend Micro 和 HTC 十餘年所學習到的經驗和知識, 提供您參考).

**Comment by f2ejack** [comment]
[紀錄] 這裡的 spec 與 closed 的 [issue #140](https://github.com/TaiBIF/camera-trap-vueapp/issues/140) 是衝突的

**Comment by f2ejack** [comment]
@cjk-halodule 請問"在伺服器回傳結果前，顯示 throbber 減輕焦慮", 是指什麼？

**Comment by f2ejack** [comment]
將下列的 To-do Items 移至 [feature/issue-#253](https://github.com/TaiBIF/camera-trap-vueapp/issues/253), 以達到 issue 最小化的原則:
- [ ] 頁面中的資料未變動前，儲存設定按鈕鎖定
- [ ] 頁面中的資料變動後，儲存前，按鈕為可按及橘色

**Comment by f2ejack** [comment]
Added loading effect when click "設定儲存"
