### ISSUE TITLE
7.3 資料篩選結果的拍攝時間時間不對

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#205]
![Screenshot 2019-05-28 16 14 34](https://user-images.githubusercontent.com/31983251/58468106-825d0d00-816f-11e9-9383-ee5bd6328d0c.png)
送出篩選查詢前沒有選定相機位置的值，而所顯示的時段與結果也無對應。

**Comment by kelp404** [comment]
@oahehc 
你把 moment 的 default tim zone 設定成 `Etc/GMT` 會讓前端沒辦法把 UTC 換成當地時間。
像第六行的 `getTodayDate = () => moment(Date.now());` 就是壞掉的。

https://github.com/TaiBIF/camera-trap-vueapp/blob/298c42323d0c4b7426c78ac0e2bb9c2890ddf80e/src/utils/dateHelper.js#L1-L6

<img width="474" alt="螢幕快照 2019-05-29 下午12 57 31" src="https://user-images.githubusercontent.com/1680868/58530443-598d5400-8211-11e9-91b4-3b9e5967b445.png">

**Comment by cjk-halodule** [comment]
@oahehc 不好意思，這個可能和我之前的解釋和誤解有關，因為 AWS 的時間都是 UTC，造成困擾請見諒。

@kelp404 另外想問，像是相機位置及計畫的時間，還有對應照片時計算的 lastModified date, 都會加上 .000z 的結尾，這邊有需要修改以維持時間的合理嗎？

因為也才發現媒體檔案名稱中有時間者，和紀錄時間目前也是相差 8 小時的情況。

**Comment by kelp404** [comment]
API 傳的全部都是 UTC+0，只有 .csv 檔用的時間是 GMT+8。
https://github.com/TaiBIF/camera-trap-api/wiki/API-v1-Document-(stop-updated)#time-format

**Comment by oahehc** [comment]
`API 傳的全部都是 UTC+0`
所以如果在 TW UTC+8 的 2019/1/1 02:00:00,
API 欄位要傳 2019-01-01T02:00:00.000Z 還是 2018-12-31T16:00:00.000Z ?

**Comment by kelp404** [comment]
```js
moment('2018-12-31T18:00:00.000Z').format('YYYY-MM-DD HH:mm')
// '2019-01-01 02:00'
```
<img width="582" alt="螢幕快照 2019-05-29 下午8 25 39" src="https://user-images.githubusercontent.com/1680868/58557023-f2db5b00-824f-11e9-8c33-b0acc423c5ee.png">

換算成瀏覽器的預設時區。

**Comment by oahehc** [comment]
這樣 user 再不同時區的看到的資料會不同, 然後就會出現這個問題喔
https://github.com/TaiBIF/camera-trap-vueapp/pull/165#issuecomment-495907521

**Comment by f2ejack** [comment]
如果時間的資料都由後端統一來處理呢？也就是後端依據user的IP得知他所在的時區，然後再換算後傳給前端

**Comment by oahehc** [comment]
轉換前後端做應該都有一樣的問題, 就是每個 user 看到的資料不一致

**Comment by cjk-halodule** [comment]
@oahehc 我想了一下，不同時區使用者看到的時間的確應該要不同，在台灣發生於 14:00 的事件，在 UTC+2 就會早上 8:00，而不能是 14:00.

以下面這筆資料為例：
```
{ 
    "_id" : ObjectId("5ce75c0ad45c04c7cf94d765"), 
    "rawData" : [
        "J01", 
        "", 
        "J01", 
        "J01-10160027_2015-10-16-15-41.JPG", 
        "2015-10-16 15:41:18", 
        "test", 
        "", 
        "", 
        "", 
        ""
    ], 
    "project" : ObjectId("5ce75c027575450a9e79b804"), 
    "studyArea" : ObjectId("5ce75c05757545dccc79b84c"), 
    "cameraLocation" : ObjectId("5ce75c057575450e6d79b84e"), 
    "uploadSession" : ObjectId("5ce75c0a757545b2ad79b867"), 
    "filename" : "J01-10160027_2015-10-16-15-41.JPG", 
    "time" : ISODate("2015-10-16T07:41:18.000+0000"),
    (省略)
 }
```
資料的原始時間 2015-10-16 15:41:18 是 +8 的時間，存到資料庫時以 UTC 記載為 2015-10-16T07:41:18.000+0000

若是在 UTC+2 的時區看，應該會是 2015-10-16 09:41:18+2000
所以我的想法是後端應該總是送 UTC (2010-07-25T04:27:48.000Z) 時間，但前端所有顯示時間的地方根據所在的時區調整；但前端在送出時間查詢時，應該要加上時區，(.800z)，後端儲存時會把時區轉成 UTC ，查詢後丟出來的資料也是 UTC，前端接手後再依所在時區顯示。

所以我想後端只要收到前端含時區的時間格式可以正確地處理，應該是不需要變動才對。若理解有錯請提出喔。

**Comment by oahehc** [comment]
我個人覺得時區跟著計劃走比較直覺.
如果某計畫是在台灣, 在 2018 年共收集了 1000 筆資料.
結果到美國去查看同一個計畫, 資料可能變成 950 筆, 我覺得好像怪怪的.

**Comment by kelp404** [comment]
我把你那行設成 UTC 拿掉後，顯示是正常的。
https://github.com/TaiBIF/camera-trap-vueapp/blob/298c42323d0c4b7426c78ac0e2bb9c2890ddf80e/src/utils/dateHelper.js#L1-L6

<img width="1245" alt="螢幕快照 2019-05-31 下午10 00 34" src="https://user-images.githubusercontent.com/1680868/58710736-957e1000-83ef-11e9-94ec-937556ce9ea6.png">

我當初設計的架構是資料庫全部都是 UTC，API 傳輸也全部都是 UTC。
csv 匯入匯出、資料計算目前是 GMT+8，但這個設定是放在 config 中，未來可以根據計畫的設定調整。
例如某個計畫是日本的，在計畫中設定 GMT+9，這樣 csv 就會全部都是慣用時間。
網頁的呈現就顯示瀏覽器的當地時間。

時區的呈現要以使用者為主。
例如明天美國早上 10:00 舉辦 WWDC，台灣的網頁為了呈現一致的時間會寫明天早上 10:00 WWDC 開始轉播嗎？
如果台灣的計畫在 31 號早上 10:00 匯入最新資料，美國看到 31 號早上 10:00 的標註不就是未來標註。

**Comment by cjk-halodule** [comment]
@oahehc 資料的查詢我想需要再做一些細膩的處理。如果某使用者在 UTC-6 以自己時區的時間查詢，結果的確會框到不同數量的資料，這時系統可提供是否按計畫時區送出查詢的選項，將 UTC-6 字面時間當作 UTC+8 來查，就可以得到和計畫時區一樣的結果。是說這個要等我們有國際化的那一天就是了。:)

**Comment by oahehc** [comment]
`我把你那行設成 UTC 拿掉後，顯示是正常的。`
=> 因為我們時區是 UTC+8, lastAnnotaionTime 是 2017/12/31 14:35,+8 還是同一年看不出錯誤。 
如果時區是在 UTC+10 或是 lastAnnotaionTime 是 2017/12/31 16:35 年份就會判斷錯誤

**Comment by kelp404** [comment]
> => 因為我們時區是 UTC+8, lastAnnotaionTime 是 2017/12/31 14:35,+8 還是同一年看不出錯誤。
> 如果時區是在 UTC+10 或是 lastAnnotaionTime 是 2017/12/31 16:35 年份就會判斷錯誤

如果 lastAnnotaionTime 是 2017-12-31T16:35:12.000Z，時間的選擇按鈕會變成 2018 年，使用者看到最後一筆 annotation 的時候用當地時間換算也會是 2018 年。

**Comment by oahehc** [comment]
> 如果 lastAnnotaionTime 是 2017-12-31T16:35:12.000Z，時間的選擇按鈕會變成 2018 年，使用者看到最後一筆 annotation 的時候用當地時間換算也會是 2018 年。

我的理解那在不同時區查詢下面這個圖表時，結果就可能會不一樣。
有時出現在 2017/12, 有時在 2018/01
![image](https://user-images.githubusercontent.com/13633490/58713522-5226a000-83f5-11e9-9b8d-4239d6677c8f.png)

**Comment by kelp404** [comment]
> 我的理解那在不同時區查詢下面這個圖表時，結果就可能會不一樣。
> 有時出現在 2017/12, 有時在 2018/01
> ![image](https://user-images.githubusercontent.com/13633490/58713522-5226a000-83f5-11e9-9b8d-4239d6677c8f.png)

那幾個圖表相關的 API 用 UTC 下去算，我明天改成 GMT+8。

**Comment by cjk-halodule** [comment]
Confirm fixed.

**Comment by kelp404** [comment]
210
