### ISSUE TITLE
篩選結果表單的呈現問題

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#206]
載入此[篩選結果](https://dev.camera-trap.tw/download/results?cameraLocations=5ce75c057575450e6d79b84e&startTime=2015-11-14T16%3A00%3A00.000Z&endTime=2015-12-01T15%3A59%3A00.000Z&timeRangeStart=-28800000&timeRangeEnd=57599999)

handsontable 的欄位呈現每次載入都會有點變化
https://www.dropbox.com/s/ls35m3cknoy66af/%E7%AF%A9%E9%81%B8%E6%AC%84%E4%BD%8D.mov?dl=0

**Comment by moogoo78** [comment]
目前看到有 2 個問題, 一個是這一行會造成 Type​Error: cyclic object value 的錯誤 (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value) 資料就卡住出不來了
https://github.com/TaiBIF/camera-trap-vueapp/blob/master/src/pages/Download/Results.vue#L322

一個是  “Error in getter for watcher “projectDataFields”: “TypeError: Cannot read property ‘zh-TW’ of undefined”"  不確定是不是資料 (projectDetail?) 那邊有缺, 還在了解中…
https://github.com/TaiBIF/camera-trap-vueapp/blob/master/src/pages/Download/Results.vue#L274-L279

**Comment by diabloevagto** [comment]
如果要同時篩選多個計畫的功能在 vuex 有需要調整的部分
1. vuex project 不支援多個計畫
2. 相機位置也不支援多個樣區

這些在 vuex 結構都是只保留最新的一個，如果要支援多個可以考慮 key, value 方式只是在取資料的時候要思考該如何方便取得

**Comment by diabloevagto** [comment]
在 data-fields 還沒取得之前隱藏 table

**Comment by cjk-halodule** [comment]
和新增多個計畫的篩選操作 請在 #234 上面 comment ，以免此 issue 關閉後不被注意到了。
