### ISSUE TITLE
離開編輯模式時若沒收起選單，選單會殘留

### ISSUE THREAD

**Issue by lyh-yihsuan** [TaiBIF/camera-trap-vueapp#213]
![螢幕快照 2019-05-29 下午3 58 00](https://user-images.githubusercontent.com/32127001/58544550-1690a800-8234-11e9-8323-3a2dcfae73dd.png)

**Comment by diabloevagto** [comment]
無法重現，關閉時會自動收回
不過問題點在於會自動選取第一個

**Comment by cjk-halodule** [comment]
剛試過在選單下拉的情況下 點選關閉編輯模式 會先取消選單 再按一次才離開編輯模式。請 @lyh-yihsuan 再看看是否仍有此問題。
