### ISSUE TITLE
編輯模式中，下拉選單點開後就一定要選一個

### ISSUE THREAD

**Issue by lyh-yihsuan** [TaiBIF/camera-trap-vueapp#214]
應該要可以不選(nullable)。
![螢幕快照 2019-05-29 下午5 09 29](https://user-images.githubusercontent.com/32127001/58544944-e39ae400-8234-11e9-82f8-bb1acb38d132.png)

**Comment by diabloevagto** [comment]
忘記那個 PR 不過已經把下拉元件改過，不會有問題了
ref #199
