### ISSUE TITLE
同時修改同 row 不同 column

### ISSUE THREAD

**Issue by diabloevagto** [TaiBIF/camera-trap-vueapp#217]
#### 問題簡述
 
同時修改 row 上面的多個不同欄位

#### 重現步驟

1. 將 row 新增兩個以上的欄位內容
2. 同時選擇多個欄位一次修改，可以按下 delete 鍵
3. api 會有錯誤，這時重新刷新頁面會發現資料沒有被刪除
...

#### 預期行為

所有欄位都被修改

#### 實際行為

有欄位沒有被修改

#### 作業環境
**作業系統及版本：**
<pre><code>

</code></pre>

**瀏覽器及版本：**
<pre><code>

</code></pre>

**Comment by cjk-halodule** [comment]
Verified.
