### ISSUE TITLE
7.3 資料篩選結果的表單顯示錯誤

### ISSUE THREAD

**Issue by moogoo78** [TaiBIF/camera-trap-vueapp#221]
#### 問題簡述
資料篩選結果頁面顯示錯誤

#### 重現步驟
https://dev.camera-trap.tw/download/results?cameraLocations=5ce75c057575450e6d79b84e&species=5cd661e332a98b60839c6caf&timeRangeStart=-28800000&timeRangeEnd=57599999

![Screen Shot 2019-05-30 at 14 22 40](https://user-images.githubusercontent.com/428769/58612922-d3434180-82e6-11e9-9b7a-2876ac2897cf.png)

**Comment by diabloevagto** [comment]
沒有 query 缺少 projectId

**Comment by moogoo78** [comment]
這個錯誤應該之前就解決了， 先 close，建議如果有其他問題再另開 issue
