### ISSUE TITLE
zip 檔內只能包單種檔案，只要混雜就會上傳錯誤

### ISSUE THREAD

**Issue by lyh-yihsuan** [TaiBIF/camera-trap-vueapp#226]
應要可以不同類型檔案（例如 csv + jpg）包在同一 zip 檔中上傳。
csv 或 jpg 或 avi 單一種類檔案打包成 zip 後上傳，已測過，皆可行。

補充說明：檔案的時間與文字資料的時間皆有完全對應，也有測試過每筆文字與每筆檔案有完全對到的狀況，結果都失敗。

供測試資料：（請參考“0531各種小量打包測試資料_供debug重現結果用”資料夾）
https://drive.google.com/open?id=1oJ32VAFNmvJabQsj_kutcGixH6FCCx7a

**Comment by kelp404** [comment]
1. 只能一個 csv。
2. 不能有資料夾。

**Comment by lyh-yihsuan** [comment]
測試時的 zip 檔中只有一個 csv，且所有檔案皆放在一起，無資料夾。

**Comment by kelp404** [comment]
根目錄有兩個 .csv 跟兩個資料夾。
<img width="1084" alt="螢幕快照 2019-06-04 上午10 45 24" src="https://user-images.githubusercontent.com/1680868/58847535-e32b9e80-86b5-11e9-81de-0ac1a61325f1.png">

**Comment by lyh-yihsuan** [comment]
不好意思！我沒有清楚指定確切 zip 檔，也忘記說明我是把所有測試用跟原始資料都放在那個連結下。

以下是拿來測試用的檔案（jpg+csv）&（avi+csv）：
https://drive.google.com/open?id=1Sn_4GPtVBwjuCLOXwnpJUWaVb9qvFSHu
https://drive.google.com/open?id=1H4FVgx86ZcKG2_f4ShSi1SWtmMr6YeJ6

**Comment by moogoo78** [comment]
@lyh-yihsuan CF-09-2_csv_avi.zip 應該是 csv 資料跟 影片資料數量不符, @kelp404 錯誤訊息沒出現在前端 
![Screen Shot 2019-06-04 at 17 14 39](https://user-images.githubusercontent.com/428769/58867015-4afcdc00-86ec-11e9-873a-3ca4e4b4c617.png)

**Comment by cjk-halodule** [comment]
請 @f2ejack 納入

**Comment by lyh-yihsuan** [comment]
這個是數量有對應到的，不知可否上傳，先放這。
https://drive.google.com/open?id=1Q_mRAOXgn6chJjVTSzW4xDXCOPhnpJF1

**Comment by kelp404** [comment]
> @kelp404 但是錯誤訊息沒出現在前端

問題已修正。 https://github.com/TaiBIF/camera-trap-api/commit/32b7395f37f37e2746da065912b5988cfa328cab

**Comment by kelp404** [comment]
> 這個是數量有對應到的，不知可否上傳，先放這。
> https://drive.google.com/open?id=1Q_mRAOXgn6chJjVTSzW4xDXCOPhnpJF1

可以上傳
<img width="1437" alt="螢幕快照 2019-06-05 上午6 47 40" src="https://user-images.githubusercontent.com/1680868/58918761-3a854980-875e-11e9-8fe9-70fa9d4a253c.png">

**Comment by moogoo78** [comment]
錯誤訊息正確了 !
<img width="1454" alt="Screen Shot 2019-06-05 at 10 14 53" src="https://user-images.githubusercontent.com/428769/58925778-59de9f80-877b-11e9-9e3f-4d8d4734a078.png">
