### ISSUE TITLE
新增完相機位置後，無法馬上接續上傳資料

### ISSUE THREAD

**Issue by lyh-yihsuan** [TaiBIF/camera-trap-vueapp#228]
如果新增完相機位置資料，沒有跳出計畫，就馬上要上傳檔案，系統會一直叫你要先建立相機位置資料（但其實已經建好了）。如果跳出計畫再進到計畫，就可以上傳。

**Comment by cjk-halodule** [comment]
@oahehc 這個是要在建立相機位置資料成功的同時也更新前端對目前有那些相機位置的資料？
