### ISSUE TITLE
即使zip檔中只有單一種類檔案，亦有可能無法上傳

### ISSUE THREAD

**Issue by lyh-yihsuan** [TaiBIF/camera-trap-vueapp#231]
此zip檔中只有兩個圖檔，不知道是不是因為單一檔案太大造成上傳失敗。https://drive.google.com/open?id=1Nxi9nyMr6oQgr9BqY07ZOzz1YU5TUMzr

**Comment by kelp404** [comment]
因為有包含一層資料夾 `zip-img`，請直接壓圖片。
