### ISSUE TITLE
針對單一資料的媒體上傳

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#235]
由於歷史資料本身常常沒有完整的詮釋資料供後端驗證及對應，故有一補上傳媒體的功能。

此項工作為在資料編輯頁面中，針對沒有媒體的資料，點選補上傳檔案：
1. 瀏覽器開 file browser 直接讓使用者選取媒體檔上傳，不再跳到`上傳頁面`
2. 上傳的如果是影片，則取得檔案的 lastModified date，加在 API 需要的變數中

API 說明 http://bit.ly/2QroO3Y

3. 上傳完成，http 200 跳出 modal 顯示「系統已收到檔案，處理中」；http 400 跳出 modal 顯示「上傳失敗，請重載頁面再試一次，若問題持續，請聯絡我們」並提供連結。

**Comment by diabloevagto** [comment]
請提供測試的影片及圖片

**Comment by cjk-halodule** [comment]
AVI https://drive.google.com/open?id=1_nMljy0PZT9i01wIvzSTMq8l43gMat49
JPG https://drive.google.com/file/d/1GS-6fvWyZCaa14g53OrI97InkQkjZUxj/view?usp=sharing

可針對任一筆沒有媒體的資料測試

**Comment by diabloevagto** [comment]
上傳完之後會馬上補上影像嗎？
目前如果上傳之後使用者要重新取回 annotation 才會看到新的影像資料，如果會馬上補上資料的話則可以上傳成功後馬上再取 annotation 資料

**Comment by cjk-halodule** [comment]
都有轉檔的時間要等，影片應該是沒有辦法，而如果遇到系統負擔重的時候，會更慢。所以先假設沒有，讓使用者過一段時間去點的時間再看到就好。

**Comment by cjk-halodule** [comment]
重新載入頁面再找到相機位置才會顯示有影片上傳成功可播放。
