### ISSUE TITLE
原本的設計是每個人都可以新增自己所負責的計畫

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#248]
From @GJWeng 
![????_2019-06-05_?? 8 57 08](https://user-images.githubusercontent.com/31983251/58925161-184cf500-8779-11e9-8fef-66705c76045e.png)

關於新增計畫的問題
我把截圖附上
我的操作步驟是：
1. 登入
2. 按「新增計畫」按鈕
3. 填寫計畫基本資料後，按「下一步」按鈕
4. 進入授權選項，填寫完後，右下角「新增計畫」按鈕是反白的，只有「取消」可以選
這應該跟權限無關
因為原本的設計是每個人都可以新增自己所負責的計畫

翁國精

**Comment by GJWeng** [comment]
補充：今年初試用的時候是沒問題的

**Comment by moogoo78** [comment]
無法重現，按照上述操作步驟， “新增計畫” 的按鈕都是顯示橘色 (不是 disable 狀態)

**Comment by cjk-halodule** [comment]
Can't reproduce.
