### ISSUE TITLE
3.1 計畫管理新增"設定儲存"按鈕的Disabled/Enabled狀態

### ISSUE THREAD

**Issue by f2ejack** [TaiBIF/camera-trap-vueapp#253]
在計畫管理的各個步驟設定頁面, 將右下角的"設定儲存"按鈕預設為 Disabled, 但是當資料有變動時, 則顯示為 Enabled.

<img width="1632" alt="螢幕快照 2019-06-06 上午5 22 05" src="https://user-images.githubusercontent.com/9169534/58991610-4125c680-881b-11e9-99ad-fecddd3c450d.png">

謝謝您！

**Comment by f2ejack** [comment]
[為了以後不再卡住相同問題, 所以暫時先予以記錄下來] 
為了做到 form 表單資料**輸入前與輸入後**的比對, 花了許多時間... 終於有所突破了, 只是為何需要這麼忙煩呢? 只能帶我有時間再來更深入 VueJS 了!! 目前的方法是先在 child component 使用 this.$parent.**projectDetail**.xxx 的方式取得預設值.

**Comment by oahehc** [comment]
建議把 PR link 過來, 知道目前怎麼做的比較容易給建議。
預設值應該是從 API 取得並放至 Vuex, 所以應該不會需要從 child component 拿才對
