### ISSUE TITLE
資料瀏覽時轉換樣區或相機位置，所在的分頁頁數不會回到第一頁

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#254]
端木老師提供。

**Comment by diabloevagto** [comment]
1. 切換樣區時 `sheet 當前頁面` 切換到第一頁以及 `sheet 單頁顯示` 改為 50 筆 ？
2. 切換所選擇的樣區位置以及篩選其他所有的篩選條件也都要跟樣區一樣都修改為第一頁及 50 筆？

**Comment by cjk-halodule** [comment]
切換樣區或相機位置代表篩選條件有變更，所以要根據新的條件從第一筆列示。
單頁顯示若使用者已經有調整過，則維持不變。

**Comment by cjk-halodule** [comment]
![Screenshot 2019-06-09 16 06 58](https://user-images.githubusercontent.com/31983251/59156621-a6561200-8ad0-11e9-88ef-76c9e98358b4.png)

功能 ok ，這個的筆數數字若能維持 aligh middle 就可以了。

**Comment by cjk-halodule** [comment]
Fixed.
