### ISSUE TITLE
Found a vulnerable dependency in a repository

### ISSUE THREAD

**Issue by f2ejack** [TaiBIF/camera-trap-vueapp#258]
Got a email notification from GitHun about vulnerable dependency:
 
Known high severity security vulnerability detected in js-yaml < 3.13.1 defined in yarn.lock.

**yarn.lock update suggested: js-yaml ~> 3.13.1.**

**Comment by diabloevagto** [comment]
重安裝就會更新了，不用調整

**Comment by cjk-halodule** [comment]
Fixed.
