### ISSUE TITLE
多個檔案上傳應能支援不同的樣區及相機位置

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#262]
![Screenshot 2019-06-07 21 29 45](https://user-images.githubusercontent.com/31983251/59107543-780af200-896b-11e9-9a4b-56aeeacb842d.png)

**Comment by diabloevagto** [comment]
現在不能嗎？

**Comment by cjk-halodule** [comment]
不能，因為後面的檔案選了樣區和相機位置後會把前面所有的樣區和相機位置的值都改成最近指定的那一個。不確定上傳是否也會是這樣，但前端的行為肯定不對囉。

**Comment by diabloevagto** [comment]
我測試正常啊
上傳選擇兩個檔案，第一個設定完之後再設定第二個檔案，兩個分別是不同的相機位置
你是不是沒有把之前的檔案取消選取？

**Comment by cjk-halodule** [comment]
噗 的確 
這個和平常桌機的操作不一樣。有沒有可能改成使用者按到其它的，原本的就取消選取，將後按 shift 才能加選一起改？

**Comment by f2ejack** [comment]
Hi All,

 

針對這裡的流程一直覺得很奇怪, 也不 user friendly. 以下是我的建議:

 
改變現有非常奇怪的樣區與相機位置設定方式 (點選樣區, 然後出現在右側選取… 為何要這麼不直覺呢?). Why? 因為即便是我以操作了N次了, 還是覺得覺得不直覺& So s….d . 建議改成直接”在欄位上”選擇前述兩者的資料. 
也許你會覺得, 這樣就不能夠一次選取很多筆資料, 然後一次設定他們的樣區和相機位置了… 說真的, 有時我們自認為靈活方便的操作方式, 未必是使用者喜歡的. 複雜&笨的操作方式, 往往是最直覺&最簡單的方式.
如果時間允許, 在選取部分, 改成 90% 網站的做法, 使用 checkbox 來表示吧!!
另外, 可以將刪除的項目, 移到另一個類似購物網站的”待購清單”, 讓下一次可以方便使用, 也不會忘記或必須重新選取&設定.
 

以上.

 

Jack Hsieh

 

寄件者: Chihjen Ko <notifications@github.com>
回覆: TaiBIF/camera-trap-vueapp <reply@reply.github.com>
日期: 2019年6月7日 星期五 下午11:57
收件者: TaiBIF/camera-trap-vueapp <camera-trap-vueapp@noreply.github.com>
副本: Subscribed <subscribed@noreply.github.com>
主旨: Re: [TaiBIF/camera-trap-vueapp] 多個檔案上傳應能支援不同的樣區及相機位置 (#262)

 

噗 的確
這個和平常桌機的操作不一樣。有沒有可能改成使用者按到其它的，原本的就取消選取，將後按 shift 才能加選一起改？

**Comment by cjk-halodule** [comment]
謝謝你的意見：
1. 這類的建議在下一個設計階段會有機會重新檢討，目前規格已訂，先在規格內優化實作
2. 目前的操作方式我個人認為算直覺，先前的 usability test 及翁老師的測試在這部分的操作均無困難，故目前只需要如我先前的回覆稍加優化即可

關於回覆方式：
1. 這是直接回覆 email 的結果嗎？請避免這樣做，或刪除不必要的部分，儘量讓 comment 的內容簡潔明確
2. 若是要 propose 一些解法，以您先前 issue 最小化的建議，我想應該是要另開一個 issue 討論，對嗎？

**Comment by f2ejack** [comment]
> 謝謝你的意見：
> 
> 1. 這類的建議在下一個設計階段會有機會重新檢討，目前規格已訂，先在規格內優化實作
> 2. 目前的操作方式我個人認為算直覺，先前的 usability test 及翁老師的測試在這部分的操作均無困難，故目前只需要如我先前的回覆稍加優化即可
> 
> 關於回覆方式：
> 
> 1. 這是直接回覆 email 的結果嗎？請避免這樣做，或刪除不必要的部分，儘量讓 comment 的內容簡潔明確
> 2. 若是要 propose 一些解法，以您先前 issue 最小化的建議，我想應該是要另開一個 issue 討論，對嗎？

瞭解. 謝謝說明 GitHub 的使用規範. :)

**Comment by diabloevagto** [comment]
修改後的行為仿照一般電腦資料夾選取方式
- 直接點擊: 單選
- 按下 shift: 範圍多選
- 按下 ctrl(windows) 或是 command(mac): 針對特定一個項目選取或取消選取
