### ISSUE TITLE
[建議] 增加"部署版號"以利 debug & fix bug

### ISSUE THREAD

**Issue by f2ejack** [TaiBIF/camera-trap-vueapp#265]
建議在Logo下方 (或頁面 Header 的固定某一個地方) 增加“版本資訊”, e.g., v1.00.01, 這樣可以讓 debug 階段在報 bug 時附加這項有用的資訊, 因為部署的版本在後期階段會快數增加, 也許某一新版本已經沒有這個問題了. 
(補充說明: 當然在 production 階段, 可以把這個部署版號放在 source code 而不對放顯示出來; 或則也可以類似 Windows App 放在一個 About Camera Trap 的 Modal 裡)

**Comment by cjk-halodule** [comment]
We actually have this https://dev.camera-trap.tw/debug.json.

**Comment by f2ejack** [comment]
Great (不過, 希望每一位參與 debug 的人都知道這項資訊, 並且在 new issue 時都註記在 issue 上.)
PS: 可能只有我這位剛進來滿一個月又多幾天的工程師不知道吧!! 謝囉!! 加油!!
