### ISSUE TITLE
3.2 計畫管理-編輯設定(3.2, 3.3.1, 9.1.2)

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#34]
/project/:projectId/setting ProjectSetting.vue

**Comment by diabloevagto** [comment]
3.2, 3.3.1 已完成
9.1.2 未完成

**Comment by cjk-halodule** [comment]
新增使用者介面回饋：

[3.1 計畫管理 (計畫基本資訊) copy.pdf](https://github.com/TaiBIF/camera-trap-vueapp/files/3155775/3.1.copy.pdf)

**Comment by melissa0520** [comment]
此部分下面是「返回」鍵，其他的（如3.1 計畫基本資訊、3.4 相機位置管理等）都是「取消」，點選取消也會返回上一頁，是否要統一名稱？
![image](https://user-images.githubusercontent.com/43326589/57825136-2b9b1f00-77d0-11e9-8e7d-2fc25b38a888.png)

**Comment by cjk-halodule** [comment]
![Screenshot 2019-05-16 20 07 15](https://user-images.githubusercontent.com/31983251/57852796-b999f880-7816-11e9-90bb-3bad32fc7316.png)

前端申請新增欄位失敗。步驟：
1. 按申請新增欄位
2. 選下拉式選單
3. 輸入選項
送出表單。

**Comment by cjk-halodule** [comment]
下載範本功能正常。

**Comment by diabloevagto** [comment]
fixed: 錯誤原因為申請新欄位 body 缺少 project id

**Comment by cjk-halodule** [comment]
表單送出功能正常。
