### ISSUE TITLE
3.4 計畫管理-相機位置管理(3.4.1, 3.5)

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#35]
/project/:projectId/camera. ProjectCamera.vue

**Comment by diabloevagto** [comment]
- [x] 3.4.1
- [x] 3.5.1 新增樣區
- [x] 3.5.5 新增子樣區
- [] 3.5.3 新增相機位置
- [] 3.5.3 編輯相機位置
- [] 3.5.3 刪除相機位置

新增部分的判斷驗證
- [] 相機位置同名判斷
- [] latitude 必填、longitude 必填 檢查

**Comment by melissa0520** [comment]
1. 新增樣區後名字無法修改，也無法刪除（子樣區和相機位置也無法刪除）

2. 新增子樣區後，母樣區仍可以新增相機位置，但在計畫裡面不會顯示

**Comment by cjk-halodule** [comment]
1. 是目前的設定，未來會再討論是否有要刪除的機制。
2. 母樣區相機位置的呈現需要再討論

**Comment by cjk-halodule** [comment]
Verified. Enhancement in separate issue #126

**Comment by cjk-halodule** [comment]
![Screenshot 2019-05-18 18 10 27](https://user-images.githubusercontent.com/31983251/57968105-deb67480-7998-11e9-8171-e02868bb8653.png)

當相機位置多時欄位呈現出現元素對齊的問題。

- [ ] 綠色標頭的寬度應隨欄位增加而齊寬
- [ ] 樣區左欄的高度應隨筆數增加與表格等高
- [ ] 右上方大地基準請改為下拉選單，有WGS84 及 TWD97 兩個選項，value 為 wgs84 及 twd97

**Comment by cjk-halodule** [comment]
@melissa0520 妳有測試過右鍵刪除嗎？

**Comment by melissa0520** [comment]
我記得我那時候有點過，但沒有成功顯示這些選項

**Comment by cjk-halodule** [comment]
Reported verified.
