### ISSUE TITLE
4.2 資料篩選區塊

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#39]
/project/:projectId/study-area/:studyAreaId{?cameraLocations,startTime,endTime,index,size,sort}

實作篩選區塊的互動操作。請注意與 7.2 可共用業務邏輯之處。

**Comment by diabloevagto** [comment]
- 下載篩選結果
- 顯示誰編輯功能
這兩個功能 api 待捕

**Comment by cjk-halodule** [comment]
後端有資料時前端應該無論如何能夠呈現；有錯或對不上的欄位則標記狀態。

https://dev.camera-trap.tw/project/5cd6631299580e3eb17fe0f3/study-areas/5cd6643c99580e819b7fe123

![Screenshot 2019-05-11 16 04 30](https://user-images.githubusercontent.com/31983251/57567101-d8f3e880-7406-11e9-971e-04b0cf8cbd5f.png)

**Comment by cjk-halodule** [comment]
相機位置點選後若無資料，handsontable 應不顯示。

https://dev.camera-trap.tw/project/5cd6631299580e3eb17fe0f3/study-areas/5cd6643c99580e819b7fe123


![Screenshot 2019-05-11 20 55 47](https://user-images.githubusercontent.com/31983251/57570031-394b5000-7430-11e9-8a09-70a14e6d3af0.png)

**Comment by diabloevagto** [comment]
fixed #116

**Comment by cjk-halodule** [comment]
https://dev.camera-trap.tw/project/5cd8c9958c607d84ddade314/study-areas/5cd8ca7b8c607d5879ade340
```        {
            "id": "5cd8fe36b47f6847298fe4e2",
            "studyArea": "5cd8ca7b8c607d5879ade340",
            "cameraLocation": "5cd8cafc8c607d2fe0ade34a",
            "failures": [],
            "filename": "01280033.MP4",
            "time": "2017-01-28T04:00:00.000Z",
            "fields": []
        },
        {
            "id": "5cd8fe36b47f6800708fe4e6",
            "studyArea": "5cd8ca7b8c607d5879ade340",
            "cameraLocation": "5cd8cafc8c607d2fe0ade34a",
            "failures": [
                "new-species"
            ],
            "filename": "01282102.MP4",
            "time": "2017-01-28T13:02:00.000Z",
            "species": {
                "id": "5cd8f975b47f68c9a98fe40c",
                "title": {
                    "zh-TW": "臺灣野豬"
                }
            },
            "fields": []
        },
```
考慮到這兩種 annotation 的情況，一個有 species ，一個沒有。若遇到後者的情況，請確保資料呈現不會因此中斷。
使用者寫入值時再依 annotation 的文件結構寫入。

**Comment by diabloevagto** [comment]
下載塞選結果 #123

**Comment by cjk-halodule** [comment]
![Screenshot 2019-05-16 16 16 47](https://user-images.githubusercontent.com/31983251/57837891-42546c80-77f6-11e9-9481-17e919ad64d1.png)

這應該要是繁體中文喔

**Comment by diabloevagto** [comment]
fixed

**Comment by cjk-halodule** [comment]
Verified.
