### ISSUE TITLE
4.3 編輯模式

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#40]
/project/:projectId/study-area/:studyAreaId{?cameraLocations,startTime,endTime,index,size,sort}

切換進入編輯模式。

**Comment by diabloevagto** [comment]
- [ ] 編輯模式中 按 `關閉編輯模式` , 確認之前的 request 都回傳 200 後解除
- [ ] 編輯模式中關閉視窗 跳出上面的提示，`你正在編輯模式，請問要離開網站嗎?`
- [ ] 停滯30分鐘無動作 自動關閉編輯模式 解鎖 對話框 “您已閒置30分鐘，系統已自動跳出編輯模式。 `我知道了` 按鈕關閉對話框

**Comment by diabloevagto** [comment]
onbeforeunload 不再提供自定義文字，簡單來說無法顯示 `你正在編輯模式，請問要離開網站嗎?`
https://developers.google.com/web/updates/2016/04/chrome-51-deprecations?hl=en#remove_custom_messages_in_onbeforeunload_dialogs

**Comment by cjk-halodule** [comment]
Should we then find our way: https://forum.vuejs.org/t/detect-browser-close/5001

**Comment by diabloevagto** [comment]
> Should we then find our way: https://forum.vuejs.org/t/detect-browser-close/5001

用的就是這個事件，但是不能自訂顯示文字

**Comment by cjk-halodule** [comment]
Verified.

**Comment by cjk-halodule** [comment]
離開頁面的確認提示需要更多確認。提示本身要確保相機位置的編輯狀態有更新。

**Comment by diabloevagto** [comment]
要怎樣更清楚的提示使用者？

> 提示本身要確保相機位置的編輯狀態有更新

這句話什麼意思

**Comment by cjk-halodule** [comment]
抱歉之前在測試時很快寫下，沒多解釋。

不是很確定先前提到的、關閉 window 時的確認是不是有作用，但我們測到的情況是兩個人同時在看同一個相機位置的資料，一人進入編輯模式，但關閉離開，另一個人不能進入編輯模式的情況。

另外一個是左欄的鎖定符號似乎和上方篩選區塊的鎖定符號不同調，常常上方的鎖定已經更新了，但左欄的沒有。

所以提示本身要確保相機位置的編輯狀態有更新的意思是，經過提示完的決定後，頁面上的視覺都要一致地更新（鎖定或解除）。

這樣理解了？

**Comment by cjk-halodule** [comment]
Related to #197

**Comment by diabloevagto** [comment]
1. 關閉 window 並不會取解除相機位置鎖定只會跳出提示，另外並不會知道使用者之後是離開還是取消。如果一定要知道就是使用者關閉的當下就馬上解除相機，設定一定秒數後再鎖定回去。但這會有問題，其他使用者在這個時間差內是可以進入的。比較理想的方式是新增一個延遲解除鎖定的 api，如果前端在時間內都沒取消就解除鎖定

2. 左欄是什麼？如果你說的是左邊的樣區選單的話，那個是不同的元件，需要補上更新的行為，不過這也僅限同一個人。不同人是不會知道要去更新資料的，除非每一秒都一直去重複取直，不然就是要用 websocket 之類的長連線由後端主動通知更新資料

**Comment by f2ejack** [comment]
To: @cjk-halodule @diabloevagto @moogoo78 
[UX] 某人一進入編輯模式後即"鎖定" (很多CMS系統也是如此的), 其他人如果有需要編輯相同的資料時, 他必須透過傳統的方式通知鎖定者是否可解除鎖定讓他進行編輯. 當然當鎖定者儲存並且離開編輯區時, 即立刻解除鎖定, 如果未儲存即離開編輯區時, 則顯示 Modal 提醒他資料未儲存, 你確定離開. 
PS: 目前我們沒有時間再新增僅作用於鎖定/解除鎖定的功能, 所以一旦離開編輯區即解除鎖定. 如果資料有更動時, 離開時也必須提醒.

**Comment by diabloevagto** [comment]
目前離開編輯模式的時候就會將相機位置鎖定解除，問題點會是在於使用者直接關閉視窗的時候到底要不要解除
並沒有辦法知道使用者在詢問是否要離開的時候按下的是 `關閉` 還是 `取消`

**Comment by cjk-halodule** [comment]
「使用者直接關閉視窗的時候到底要不要解除」在實作上成本較高，暫不考慮了。
目前的問題在於其它人進入編輯模式前，所顯示的相機位置鎖定狀態是否最新。這在連接的 issue 處理。
