### ISSUE TITLE
4.5 編輯模式 (表單欄位)

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#42]
/project/:projectId/study-area/:studyAreaId{?cameraLocations,startTime,endTime,index,size,sort}

**Comment by diabloevagto** [comment]
連拍時間提示在 4.11 實作，其他皆完成

**Comment by cjk-halodule** [comment]
尚缺新增欄位，連到計畫管理頁面的連結。

**Comment by diabloevagto** [comment]
> 尚缺新增欄位，連到計畫管理頁面的連結。

這什麼意思？

**Comment by cjk-halodule** [comment]
![Screenshot 2019-05-16 21 03 05](https://user-images.githubusercontent.com/31983251/57855798-1c42c280-781e-11e9-8414-1a08212206dd.png)
![Screenshot 2019-05-16 21 04 14](https://user-images.githubusercontent.com/31983251/57855826-2d8bcf00-781e-11e9-950c-809307da665d.png)

**Comment by cjk-halodule** [comment]
![Screenshot 2019-05-18 13 38 45](https://user-images.githubusercontent.com/31983251/57965225-0810d980-7974-11e9-8a86-5d8aac505412.png)

還有一條線 :)

**Comment by cjk-halodule** [comment]
這個好像只有有資料的時候線底框才會不見

**Comment by diabloevagto** [comment]
那條線是第一行的資料補上的 border-top ，因為我把 header `+` 底下所有的 cell 都隱藏所以才會消失
如果有捲動時會在 header 補上 border-bottom
這些都是 handsontable 的機制，我如果在一開始補上那條線，但是當資料捲動時就會被 handsontable 再把 css 樣式移除掉

**Comment by cjk-halodule** [comment]
瞭解

**Comment by cjk-halodule** [comment]
目前無法按及新增欄位

**Comment by cjk-halodule** [comment]
在篩選結果及資料編輯頁面目前均無功能。在篩選結果頁面重載[+]有時會跑到第一欄。

**Comment by diabloevagto** [comment]
修復 `資料編輯頁面` 的 `+` 連結功能
