### ISSUE TITLE
4.9 編輯模式 (操作相關 下拉物種清單 )

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#46]
實作下拉物種選單。

![Screenshot 2019-05-11 16 13 30](https://user-images.githubusercontent.com/31983251/57567169-ca5a0100-7407-11e9-842f-4c38f33ced65.png)

**Comment by cjk-halodule** [comment]
此處使用者可輸入資料，而下拉物種清單由計畫預設物種清單提供待選。

focus 離開 cell 位置時，若使用者輸入的物種名字不在系統紀錄中，則系統則新增該物種，並添加至計畫物種清單中，因此不會有 4.17.2 的異常提示。

各計畫同一物種名稱不同的問題，另開 issue 處理。

**Comment by cjk-halodule** [comment]
https://dev.camera-trap.tw/project/5cd6631299580e3eb17fe0f3/study-areas/5cd6643c99580e819b7fe123
HL11A 的資料

進入編輯模式 嘗試 編輯物種
1. 雙擊第一筆「測試」，進入編輯狀態，選定「人」，按下 Enter
![Screenshot 2019-05-15 11 27 20](https://user-images.githubusercontent.com/31983251/57746763-39d03900-7705-11e9-8f88-a50cbb773122.png)

2. 仍顯示為「測試」，再雙擊又會顯示「人」
![Screenshot 2019-05-15 11 27 34](https://user-images.githubusercontent.com/31983251/57746768-4359a100-7705-11e9-8f69-5ce614fd2a35.png)

Concole 報錯
![Screenshot 2019-05-15 11 26 59](https://user-images.githubusercontent.com/31983251/57746820-7a2fb700-7705-11e9-82f4-21fd44202f13.png)

**Comment by diabloevagto** [comment]
這應該已經 ok 了吧？
如果沒問題就可以 close

**Comment by cjk-halodule** [comment]
yes.
