### ISSUE TITLE
4.10 編輯模式 (操作相關 滑鼠右鍵)

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#47]
實作滑鼠右鍵功能。「貼上」不能點選，但顯示「 貼上 請使用鍵盤 ctrl+v 或 cmd+v」

**Comment by cjk-halodule** [comment]
新增一筆紀錄 related to https://github.com/TaiBIF/camera-trap-api/issues/132

**Comment by cjk-halodule** [comment]
復原的話看看如果可暫時把刪除的紀錄 id 暫存在 cookie 中，以一次操作包起來，選復原時就以最近的一包分別把 annotations 從 delete 的狀態再設成 active. 這個目前 API 需要能以狀態篩選

**Comment by diabloevagto** [comment]
為了滿足刪除列的規則需新增 api 欄位 https://github.com/TaiBIF/camera-trap-api/issues/180

刪除列規則 note
```
該筆資料刪完後會導致該相機位置沒有資料，就不給刪
表示不能直接用篩選回來的資料筆數判斷能不能刪除
因為有可能選了多個相機位置，但是我把其中一個相機位置全部刪掉，但是資料筆數還是一樣不會為 0
例如我相機位置選了 A, B, C 三個，然後個別有 5, 10, 15 筆資料
這時候我刪除了 10 筆，如果直接判斷總數是可以刪除
但是我要刪除的資料有可能包含了 A 的 5 筆，這樣刪除之後 A 就會沒有資料
```

**Comment by diabloevagto** [comment]
- 複製列及刪除列實作完成
- 復原及重做暫時預留選單但不實作

**Comment by cjk-halodule** [comment]
... 必須承認我怎麼點都是 macOS 的右鍵 .. any tips?

**Comment by cjk-halodule** [comment]
要記得按編輯模式才有右鍵可用。
