### ISSUE TITLE
4.12 連拍自動補齊 (滑鼠右鍵)

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#49]
實作 4.12 連拍自動補齊 (滑鼠右鍵)

**Comment by cjk-halodule** [comment]
請將對話框寬度安排在兩行字？
![Screenshot 2019-05-24 22 39 17](https://user-images.githubusercontent.com/31983251/58335794-eed8c300-7e74-11e9-91b5-797dc139bd74.png)

![Screenshot 2019-05-24 22 39 19](https://user-images.githubusercontent.com/31983251/58335804-f6986780-7e74-11e9-92f8-c2550b4f1fcf.png)
連拍自動補齊按鈕及文字高度的中間和左邊的「共107筆資料」對齊，所以按鈕上下的 margin 是一樣的。

**Comment by diabloevagto** [comment]
> 連拍自動補齊按鈕及文字高度的中間和左邊的「共107筆資料」對齊，所以按鈕上下的 margin 是一樣的。

這什麼意思？目前沒對齊嗎？

**Comment by cjk-halodule** [comment]
![Screenshot 2019-05-25 17 45 33](https://user-images.githubusercontent.com/31983251/58367727-f3ed4f00-7f14-11e9-909b-f56f76164287.png)
B > A

sorry - 不應該假設是margin. 視覺上，整個按鈕的中線和左邊文字的中線沒有對齊。這個情況可能也和「連拍自動補齊」字樣和按鈕邊界上下不一樣也有關係。但重點是看起來所有的字雖然大小不一樣，希望它們的中線可以對齊。

**Comment by diabloevagto** [comment]
- [x] 對話框寬度安排在兩行字
- [ ] 連拍自動補齊按鈕及文字高度的中間和左邊的「共107筆資料」對齊

**Comment by diabloevagto** [comment]
我先發一個 PR ，對齊的部分我看起來都一樣
看是否 @oahehc 或是其他視覺設計有什麼想法再修正

**Comment by cjk-halodule** [comment]
但是這個 issue 重點是滑鼠右鍵的那個「解除連拍連結」喔
![Screenshot 2019-05-25 18 50 16](https://user-images.githubusercontent.com/31983251/58368327-fef8ad00-7f1d-11e9-96b3-89898f6a4e81.png)

**Comment by diabloevagto** [comment]
解除連拍怎麼了嗎？

**Comment by cjk-halodule** [comment]
已測試。功能運作正常。👍
