### ISSUE TITLE
4.15 影像檢視區塊 (影片)

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#52]
實作 4.15 影像檢視區塊 (影片)

參考[此頁](https://surmon-china.github.io/vue-video-player/)的第一個範例：
![Screenshot 2019-05-19 18 01 07](https://user-images.githubusercontent.com/31983251/57980614-3ec41e00-7a60-11e9-8ac3-96f84e29be14.png)

- [x] 功能：播放、停止、聲音、播放進度、速度、全螢幕
- [x] 當一筆結束自動播放下一筆，下一筆如果是影片就繼續播放，如果是圖片就暫停

目前一筆紀錄只會有一筆媒體檔案。

另外，若該筆資料沒有媒體而顯示「補上傳影像檔」，則按下按鈕不導向檔案上傳頁面，而是瀏覽器開 file selector 利用 [/annoations/{annotationId}/file{?type,lastModified}](http://bit.ly/2EjU7Zt)直接上傳資料。

**Comment by cjk-halodule** [comment]
- [ ] 自動播放

**Comment by cjk-halodule** [comment]
剛上傳的一筆影片在 https://dev.camera-trap.tw/project/5cd8c9958c607d84ddade314/study-areas/5cd8ca7b8c607d5879ade340 草坔01 第一筆，請試看看如何可讓前端撥放囉。

**Comment by diabloevagto** [comment]
1. 是否可能同時有影片也有照片
2. 影片播放功能有那些
3. 當一筆結束是否要自動播放下一筆 annotation ?那下一筆如果是影片就繼續播放，那如果是圖片就暫停換成圖片？

**Comment by diabloevagto** [comment]
有些遊覽器預設會將影片自動播放阻擋
