### ISSUE TITLE
4.17 錯誤提示

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#54]
實作錯誤提示

**Comment by diabloevagto** [comment]
#95

**Comment by cjk-halodule** [comment]
![Screenshot 2019-05-16 17 41 01](https://user-images.githubusercontent.com/31983251/57844031-d841c480-7801-11e9-8b97-32990c520b08.png)

這和 WF 的提示方式不一樣喔，應該是：
![Screenshot 2019-05-16 17 42 16](https://user-images.githubusercontent.com/31983251/57844116-ff989180-7801-11e9-834a-770aa945f7e3.png)

**Comment by cjk-halodule** [comment]
也請看看這支是否夠用囉 https://github.com/TaiBIF/camera-trap-api/issues/79

**Comment by cjk-halodule** [comment]
上面的滑入提示要記得到左邊喔

**Comment by cjk-halodule** [comment]
更正一下，這裡的錯誤應該不是實作成滑入提示，而是如上面把錯誤報在浮出訊息 bar 可以按 X 關掉。

但其他地方的滑入提示就要放到左邊。

**Comment by diabloevagto** [comment]
> 也請看看這支是否夠用囉 [TaiBIF/camera-trap-api#79](https://github.com/TaiBIF/camera-trap-api/issues/79)

1. api 是否已經將錯誤都實作完成了？看文件的 failures 還是只有 `new-species` 一種
2. 如果已經實作完成是否有樣區能提供所有測試情況？
3. 請定義所有錯誤情況要顯示的文字訊息，WF 只有一種而已

**Comment by diabloevagto** [comment]
如果還沒完成我就先改顯示方式，錯誤訊息之後在測試

**Comment by diabloevagto** [comment]
`物種名稱不在預設中，請修正名稱，或回報管理員`

`回報管理員` 在 WF 內是連結，那是要連到那邊？或是有什麼其他的行為

**Comment by cjk-halodule** [comment]
連到 聯絡我們

**Comment by cjk-halodule** [comment]
目前的確只有這 new-species 這一種，所以先處理這項就好囉。

**Comment by diabloevagto** [comment]
failures 這個欄位是 array ，那是否表示之後有可能會有多筆？
如果可以有多種錯誤的話，提示行為之後也要記得規劃

**Comment by cjk-halodule** [comment]
Feature verified.
