### ISSUE TITLE
4.18 滑入提示 

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#55]
實作滑入提示

4.18.1 中間的「拖曳拉大影像檢視範圍」請參考
https://github.com/TaiBIF/camera-trap-webapp/blob/6dba58a6915d156020455db524bc8becd5749695/src/pages/index/views/Site.vue#L367 的 <zoom-drag>

**Comment by diabloevagto** [comment]
- [ ] 連拍提示
- [ ] 學名提示
- [ ] 拖移拉大影像檢視範圍提示
