### ISSUE TITLE
5.3 5.4 上傳流程; 5.6 5.7 進行上傳

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#59]
/project/:projectId/upload. ProjectUpload.vue.

**Comment by diabloevagto** [comment]
尚缺項目
- [ ] 5.7.1 (1) 畫面右上角 `剩餘時間` 及 `上傳完成` 提示
- [ ] 5.7.1 (4) `查看` 功能及 `檢視錯誤`
- [ ] 5.8

**Comment by cjk-halodule** [comment]
目前上傳的檔案選擇，大寫的 MP4 不能選，是和大小寫有關嗎？
![Screenshot 2019-05-16 17 35 56](https://user-images.githubusercontent.com/31983251/57843576-1d192b80-7801-11e9-8b7a-d18802b65a2d.png)

**Comment by diabloevagto** [comment]
檔案不上傳原因是沒有設定成能被選取的檔案
目前能上傳檔案類別是寫在 `src/constant/uploadAccept.js` 裡面，只要把上傳的 mp4 檔案 accept 型態寫進去就好
目前有那些影片是可以上傳的？能否提供測試範例

**Comment by cjk-halodule** [comment]
這部分應該要保持和 https://github.com/TaiBIF/camera-trap-api/blob/72a75a31a1e9da9856dc34eeb3a75b5dae06e84a/src/models/const/file-extension-name.js#L3 對應。在此註記。

**Comment by cjk-halodule** [comment]
![Screenshot 2019-05-20 22 50 24](https://user-images.githubusercontent.com/31983251/58030777-bb82f500-7b51-11e9-9701-fde06ab28c68.png)

點選「檢閱詳細上傳說明」沒有反應，且 console 報錯

**Comment by diabloevagto** [comment]
fixed, 我直接改在 master

**Comment by cjk-halodule** [comment]
Verified.
