### ISSUE TITLE
5.8 錯誤狀態

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#63]
實作錯誤狀態對話 modal

**Comment by diabloevagto** [comment]
可參考 `DoubleCheckModal.vue` 這個檔案修改，改成只有一個按鈕

**Comment by moogoo78** [comment]
@diabloevagto  如果上傳一個沒有 exif 的圖檔，API 就會回傳 400 (Bad Request)，前端就拿不到 error message，是不是要在 utils/fetch.js 的fetchUpload 加回傳的判斷? ( fetchWrap 那邊有做 )
![Screen Shot 2019-05-21 at 14 43 35](https://user-images.githubusercontent.com/428769/58074239-5a056980-7bd7-11e9-8db4-b9fd9890066f.png)

**Comment by cjk-halodule** [comment]
上傳那邊只有 http status 可以用，要給更多的細節應該還是要配合 upload session 的結果處理，前端可以更 aggressive 一點過 5s 就去抓 upload session 的狀態，或甚至是做 push notification. 但這個 issue 可以了。謝謝。
