### ISSUE TITLE
6.1-2 上傳紀錄

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#64]
/upload-history. UploadHistory.vue

實作上傳紀錄頁面 6.1, 6.2

**Comment by moogoo78** [comment]
錯誤訊息跟之前版本不一樣, 現在參考:
https://github.com/TaiBIF/camera-trap-api/blob/master/src/models/const/upload-session-error-type.js

**Comment by diabloevagto** [comment]
PR #134 待調整項目
1. store 裡面沒意義的註解都要刪掉
2. store 裡面的 getter 作用是什麼？並沒有用到
3. 元件 `<tr>` 的 key 直接用 id 就好，不需要加上 `trow`
4. 錯誤 modal 改成共用資料用 slot 丟進去，只有一個確認按鈕的有可能之後也會用到

**Comment by moogoo78** [comment]
@diabloevagto 
- 已修改 1~3
- 移除 UploadSessionsErrorModel, 新增 InfoModal (只有一個確認按鈕)
- 目前沒發現, 不知道是不是問題 2 的 code 造成的

**Comment by cjk-halodule** [comment]
Verified.
