### ISSUE TITLE
7.1, 7.2 篩選及下載 

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#65]
/download/search  DownloadSearch.vue.

實作資料搜尋操作

**Comment by cjk-halodule** [comment]
https://github.com/TaiBIF/camera-trap-api/issues/154#issuecomment-490733159

**Comment by f2ejack** [comment]
@cjk-halodule 點選"篩選及下載"之後, 如果都沒有 Project, 是否應該呈現"新增計畫"的頁面 (同點選"計畫總覽"之後但是沒有計畫時一樣), 只是標題是"篩選及下載"?

**Comment by cjk-halodule** [comment]
結論是如果使用者沒有任何計畫，則篩選及下載選單將淡色呈現，無法點選。

**Comment by cjk-halodule** [comment]
Verified.
