### ISSUE TITLE
10.1 帳號設定, 10.2 快速鍵設定(10.1.2)

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#71]
/setting  Setting.vue  10.1 帳號設定, 10.2 快速鍵設定(10.1.2) -> wait API

**Comment by oahehc** [comment]
wait for API
https://github.com/TaiBIF/camera-trap-api/issues/96

**Comment by cjk-halodule** [comment]
帳號中  ORCiD 的連結有 cursor 但點了沒有動作

![Screenshot 2019-05-08 19 16 21](https://user-images.githubusercontent.com/31983251/57371710-0e5dc380-71c6-11e9-9f9f-a1dddd2dfcb2.png)

**Comment by cjk-halodule** [comment]
剛試了一下 使用 https://orcid.org/my-orcid 應是合理的。如果有登入的話就可以進入 ORCiD 的設定頁面。 我來更新 WF.

**Comment by cjk-halodule** [comment]
Verified.
