### ISSUE TITLE
11.1 通知 

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#72]
見 https://cameratraptw.docs.apiary.io/#/reference/system/notifications
實作通知。

**Comment by oahehc** [comment]
wait for API ready and spec
https://github.com/TaiBIF/camera-trap-api/issues/25

**Comment by cjk-halodule** [comment]
1. 只顯示 20 筆，捲動沒說清楚 是指如果太長超過視窗高度的話
2. 目前的想法是滑鼠點選在訊息區塊上面 利用視覺改變標本已讀 視覺改變待定義

**Comment by cjk-halodule** [comment]
[11.1 通知.pdf](https://github.com/TaiBIF/camera-trap-vueapp/files/3145268/11.1.pdf

@oahehc  這樣視覺是否清楚些？

**Comment by oahehc** [comment]
wait for API and spec: https://github.com/TaiBIF/camera-trap-api/issues/147

**Comment by cjk-halodule** [comment]
謝謝點出問題，這些其實表示目前尚有許多細節操作需要建立，大部分應該是留到下階段比較合理。
> a 欄位申請核准頁面會再設計畫面嗎？這頁面預計 20 號前不太可能完成
![image](https://user-images.githubusercontent.com/31983251/57711102-b2e97500-76a0-11e9-98b0-525def68a59c.png)

下階段才會，申請核准目前會是系統端口頭與各計畫主持人聯絡過後，再手動送 API call 核准。故目前不需實作。

> b 這邊的後台介面是指哪邊？
![image](https://user-images.githubusercontent.com/31983251/57711159-cf85ad00-76a0-11e9-8460-9e9af83baa83.png)

這部分沒有設計。暫以人工 email 進行。故目前不需實作。

> c reject 的 wording & action?
![image](https://user-images.githubusercontent.com/31983251/57711193-ddd3c900-76a0-11e9-9c95-39690a7ab90c.png)

Reject 的原因將會因情況有很多變化，目前 API 亦未設計輸入原因，故 reject 的 case 留待下階段。

> `檢視異常資料`要連到的頁面是哪一頁？4.1 資料編輯? 
![image](https://user-images.githubusercontent.com/31983251/57711243-f0e69900-76a0-11e9-9659-b3c5c33ac9f6.png)

是的。

> f 沒有 type, 是還沒定義嗎？
![image](https://user-images.githubusercontent.com/31983251/57711281-0360d280-76a1-11e9-9fca-fdca68b13ebf.png)

發現這個也因為 b 沒有後台的設計，故還有設計細節待補足，下階段再執行。

> 取消上傳 & 取代重複的資料是會開 api, 還是點擊要連去其他頁面？
![image](https://user-images.githubusercontent.com/31983251/57711361-24292800-76a1-11e9-8b24-bf2c8215c401.png)

[這裡](https://github.com/TaiBIF/camera-trap-api/issues/82#issuecomment-488545574)有 API 可用。不需連到其它介面。點選後回傳 204 在原連結位置顯示「已取消」或「已覆蓋」。

> 問題回報/意見反饋 指的是聯絡我們這頁面？如果是這頁, user 發送時應該不會有對應的計畫？

是的，但看起來是聯絡我們表單需要新增計畫欄位。

**Comment by cjk-halodule** [comment]
通知功能目前的狀態可以了。其餘下階段再釐清。
