### ISSUE TITLE
12.2, 12.3 聯絡我們

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#74]
/help/contact-us  HelpContactUs.vue. 12.2 聯絡我們(12.2.2 ~ 12.2.5, 12.3)

**Comment by oahehc** [comment]
wait for API: https://github.com/TaiBIF/camera-trap-api/issues/90

**Comment by kelp404** [comment]
API 已經好了
https://cameratraptw.docs.apiary.io/#/reference/issues/create-an-issue/create-an-issue/200?mc=reference%2Fissues%2Fcreate-an-issue%2Fcreate-an-issue%2F200
https://github.com/TaiBIF/camera-trap-api/issues/90

**Comment by melissa0520** [comment]
寫了問題回報送出後，我留的信箱沒有收到通知
官方信箱 cameratrap.taibif@gmail.com 也沒有收到通知

**Comment by kelp404** [comment]
帳號沒設定 email，我剛剛加上去了。
<img width="940" alt="螢幕快照 2019-05-16 上午11 45 56" src="https://user-images.githubusercontent.com/1680868/57825141-305fd300-77d0-11e9-9d02-e13a54ef2278.png">

**Comment by melissa0520** [comment]
剛剛測試一樣沒有收到唷

**Comment by kelp404** [comment]
你是哪一個帳號？
現在資料庫有填 email 的帳號只有兩個。
<img width="865" alt="螢幕快照 2019-05-16 下午2 24 35" src="https://user-images.githubusercontent.com/1680868/57830985-660fb680-77e6-11e9-8807-9919f602e58d.png">

系統有把信發給所有管理員。
<img width="989" alt="螢幕快照 2019-05-16 下午2 23 20" src="https://user-images.githubusercontent.com/1680868/57831016-7f186780-77e6-11e9-9d0d-c2e89f76cb53.png">

**Comment by melissa0520** [comment]
melissaliu0520@gmail.com 這個

**Comment by kelp404** [comment]
https://github.com/TaiBIF/camera-trap-api/issues/90#issuecomment-489299204
> 我會改成不發信給提出問題的人，因為規格上沒有。
> 發信給管理員會保留但這也是不在規格上的。

使用者提出問題後，會發站內通知「Notification」然後寄 email 給所有系統管理員，並不會寄 email 給提出問題的人。

**Comment by melissa0520** [comment]
OK，我瞭解了，本來以為應該是cameratrap.taibif@gmail.com這個信箱也會收到通知，現在知道系統管理員有收到就好了。

**Comment by cjk-halodule** [comment]
Verified.
