### ISSUE TITLE
2.10 相機異常回報 

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#81]
實作相機異常回報

**Comment by oahehc** [comment]
wait for API: https://github.com/TaiBIF/camera-trap-api/issues/123

**Comment by oahehc** [comment]
畫面完成待接 API: https://github.com/TaiBIF/camera-trap-vueapp/pull/88

**Comment by cjk-halodule** [comment]
Form verified.
